
import { IntlLocalizationAdapter } from "../../src/DataTypes/IntlLocalizationAdapter";
import { StringLookupKey, CaseInsensitiveStringLookupKey, CapitalizeStringLookupKey, UppercaseStringLookupKey, LowercaseStringLookupKey, NumberLookupKey, CurrencyLookupKey, PercentageLookupKey, BooleanLookupKey, YesNoBooleanLookupKey, DateTimeLookupKey, DateLookupKey, AbbrevDateLookupKey, AbbrevDOWDateLookupKey, LongDateLookupKey, LongDOWDateLookupKey, TimeOfDayLookupKey, TimeOfDayHMSLookupKey } from "../../src/DataTypes/LookupKeys";
describe('LocalizationAdapter.IntlLocalizationAdapter CultureID and fallbackCultureIDs functions', () => {
    test('EN CultureID, no fallback', () => {
        let la = new IntlLocalizationAdapter('en');
        expect(la.CultureID).toBe('en');
        expect(la.FallbackCultureID).toBeNull();
        expect(la.Currency).toBe('USD');
    });
    test('en-GB CultureID, en fallback', () => {
        let la = new IntlLocalizationAdapter('en-GB', 'en');
        expect(la.CultureID).toBe('en-GB');
        expect(la.FallbackCultureID).toBe('en');
        expect(la.Currency).toBe('USD');
    });    
    test('Currency set', () => {
        let la = new IntlLocalizationAdapter('en-GB', 'en', 'GBP');
        expect(la.Currency).toBe('GBP');
    });        
});

describe('LocalizationAdapter.IntlLocalizationAdapter class preregistered ToString functions', () => {
    test('StringLookupKey with string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', StringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('A');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('StringLookupKey with number is converted to string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(15, StringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('15');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });    
    test('StringLookupKey with null is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, StringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });    
    test('StringLookupKey with undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(undefined, StringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('StringLookupKey with object is an error', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, StringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a string or primitive');
        expect(dtr.NotFound).toBeUndefined();
    });    
    test('CaseInsensitiveLookupKey with string returns the string verbatim', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', CaseInsensitiveStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('A');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('a', CaseInsensitiveStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('a');
    });    
    test('CapitalizeStringLookupKey with string returns the string with first letter capitalized', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', CapitalizeStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('A');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('a', CapitalizeStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('A');
        dtr = la.ToString('abc', CapitalizeStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Abc');        
        dtr = la.ToString('', CapitalizeStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');        
    });        
    test('UppercaseStringLookupKey with string returns the string in uppercase', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', UppercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('A');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('a', UppercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('A');
        dtr = la.ToString('abc', UppercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('ABC');        
        dtr = la.ToString('', UppercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');        
    });            
    test('LowercaseStringLookupKey with string returns the string in lowercase', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', LowercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('a');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('a', LowercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('a');
        dtr = la.ToString('abc', LowercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('abc');        
        dtr = la.ToString('ABC', LowercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('abc');
        dtr = la.ToString('', LowercaseStringLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');        
    });            
    test('NumberLookupKey in en culture with various valid numbers', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(1, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(1.5, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1.5');
        dtr = la.ToString(1000000, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1,000,000');
        dtr = la.ToString(-9.50101, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('-9.501');
    });

    test('NumberLookupKey in fr culture with various valid numbers', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(1, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(1.5, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1,5');
        dtr = la.ToString(1000000, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1\u{202F}000\u{202F}000');
        dtr = la.ToString(-9.50101, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('-9,501');
    });    
    test('NumberLookupKey in en culture with ways to output empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
    });
    test('NumberLookupKey with invalid type returns NotFound', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', NumberLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a number');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString({}, NumberLookupKey);
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a number');
        expect(dtr.NotFound).toBeUndefined();
    });
    test('CurrencyLookupKey in en culture with various valid numbers', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(1, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('$1.00');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(1.5, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('$1.50');
        dtr = la.ToString(1000000, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('$1,000,000.00');
        dtr = la.ToString(-9.50101, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('-$9.50');
    });

    test('CurrencyLookupKey in fr culture with various valid numbers', () => {
        let la = new IntlLocalizationAdapter('fr', null, 'EUR');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(1, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1,00\xA0€');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(1.5, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1,50\xA0€');
        dtr = la.ToString(1000000, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1\u{202F}000\u{202F}000,00\xA0€');
        dtr = la.ToString(-9.50101, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('-9,50\xA0€');
    });    
    test('CurrencyLookupKey in en culture with ways to output empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
    });    
    test('CurrencyLookupKey with invalid type returns NotFound', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', CurrencyLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a number');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString({}, CurrencyLookupKey);
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a number');
        expect(dtr.NotFound).toBeUndefined();
    });    
    test('PercentageLookupKey in en culture with various valid numbers', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(1, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('100%');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(0.15, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('15%');
        dtr = la.ToString(1000, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('100,000%');
        dtr = la.ToString(-0.09, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('-9%');
    });

    test('PercentageLookupKey in fr culture with various valid numbers', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(1, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('100\xA0%');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(0.15, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('15\xA0%');
        dtr = la.ToString(1000, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('100\u{202F}000\xA0%');
        dtr = la.ToString(-0.09, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('-9\xA0%');
    });    
    test('PercentageLookupKey in en culture with ways to output empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
    });
    test('PercentageLookupKey with invalid type returns NotFound', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', PercentageLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a number');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString({}, PercentageLookupKey);
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a number');
        expect(dtr.NotFound).toBeUndefined();
    });
    test('BooleanLookupKey with true or false is "true" or "false"', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(true, BooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('true');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(false, BooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('false');
    });
    test('BooleanLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, BooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, BooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
    });    
    test('BooleanLookupKey with invalid type returns NotFound', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', BooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a boolean');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(1, BooleanLookupKey);
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a boolean');
        expect(dtr.NotFound).toBeUndefined();
    });
    test('YesNoBooleanLookupKey with true or false is "yes" or "no"', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(true, YesNoBooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('yes');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(false, YesNoBooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('no');
    });
    test('YesNoBooleanLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, YesNoBooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, YesNoBooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
    });    
    test('YesNoBooleanLookupKey with invalid type returns NotFound', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString('A', YesNoBooleanLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a boolean');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(1, YesNoBooleanLookupKey);
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a boolean');
        expect(dtr.NotFound).toBeUndefined();
    });    
    test('DateTimeLookupKey in en culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('10/31/2000, 12:00 AM');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1/1/1980, 4:00 AM');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1/15/1980, 4:04 PM');
    });

    test('DateTimeLookupKey in fr culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('31/10/2000 00:00');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('01/01/1980 04:00');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('15/01/1980 16:04');
    });    
    test('DateTimeLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('DateTimeLookupKey with values other than Date, null or undefined are errors', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('', DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(10, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();    
        dtr = la.ToString(true, DateTimeLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();        
    });

    test('DateLookupKey in en culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('10/31/2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1/1/1980');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1/15/1980');
    });

    test('DateLookupKey in fr culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('31/10/2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('01/01/1980');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('15/01/1980');
    });    
    test('DateLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('DateLookupKey with values other than Date, null or undefined are errors', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('', DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(10, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();    
        dtr = la.ToString(true, DateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();        
    });

    test('AbbrevDateLookupKey in en culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Oct 31, 2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Jan 1, 1980');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Jan 15, 1980');
    });

    test('AbbrevDateLookupKey in fr culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('31 oct. 2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1 janv. 1980');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('15 janv. 1980');
    });    
    test('AbbrevDateLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('AbbrevDateLookupKey with values other than Date, null or undefined are errors', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('', AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(10, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();    
        dtr = la.ToString(true, AbbrevDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();        
    });
    test('AbbrevDOWDateLookupKey in en culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Tue, Oct 31, 2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 2, 4, 0, 30);
        dtr = la.ToString(date2, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Wed, Jan 2, 1980');
        let date3 = new Date(1980, 0, 18, 16, 4, 0);        
        dtr = la.ToString(date3, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Fri, Jan 18, 1980');
    });

    test('AbbrevDOWDateLookupKey in fr culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('mar. 31 oct. 2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 3, 4, 0, 30);
        dtr = la.ToString(date2, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('jeu. 3 janv. 1980');
        let date3 = new Date(1980, 0, 18, 16, 4, 0);        
        dtr = la.ToString(date3, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('ven. 18 janv. 1980');
    });    
    test('AbbrevDOWDateLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('AbbrevDOWDateLookupKey with values other than Date, null or undefined are errors', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('', AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(10, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();    
        dtr = la.ToString(true, AbbrevDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();        
    });    
    test('LongDateLookupKey in en culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('October 31, 2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('January 1, 1980');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('January 15, 1980');
    });

    test('LongDateLookupKey in fr culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('31 octobre 2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('1 janvier 1980');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('15 janvier 1980');
    });    
    test('LongDateLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('LongDateLookupKey with values other than Date, null or undefined are errors', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('', LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(10, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();    
        dtr = la.ToString(true, LongDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();        
    });
    test('LongDOWDateLookupKey in en culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Tuesday, October 31, 2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 2, 4, 0, 30);
        dtr = la.ToString(date2, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Wednesday, January 2, 1980');
        let date3 = new Date(1980, 0, 18, 16, 4, 0);        
        dtr = la.ToString(date3, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('Friday, January 18, 1980');
    });

    test('LongDOWDateLookupKey in fr culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('mardi 31 octobre 2000');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 3, 4, 0, 30);
        dtr = la.ToString(date2, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('jeudi 3 janvier 1980');
        let date3 = new Date(1980, 0, 18, 16, 4, 0);        
        dtr = la.ToString(date3, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('vendredi 18 janvier 1980');
    });    
    test('LongDOWDateLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('LongDOWDateLookupKey with values other than Date, null or undefined are errors', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('', LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(10, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();    
        dtr = la.ToString(true, LongDOWDateLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();        
    });        

    test('TimeOfDayLookupKey in en culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('12:00 AM');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('4:00 AM');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('4:04 PM');
    });

    test('TimeOfDayLookupKey in fr culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('00:00');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('04:00');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('16:04');
    });    
    test('TimeOfDayLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('TimeOfDayLookupKey with values other than Date, null or undefined are errors', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('', TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(10, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();    
        dtr = la.ToString(true, TimeOfDayLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();        
    });    
    test('TimeOfDayLookupKey in en culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('12:00:00 AM');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('4:00:30 AM');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('4:04:00 PM');
    });

    test('TimeOfDayHMSLookupKey in fr culture with various valid dates', () => {
        let la = new IntlLocalizationAdapter('fr');
        la.RegisterBuiltInLookupKeyFunctions();
        let date1 = new Date(2000, 9, 31);
        let dtr = la.ToString(date1, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('00:00:00');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        let date2 = new Date(1980, 0, 1, 4, 0, 30);
        dtr = la.ToString(date2, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('04:00:30');
        let date3 = new Date(1980, 0, 15, 16, 4, 0);        
        dtr = la.ToString(date3, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('16:04:00');
    });    
    test('TimeOfDayHMSLookupKey with null or undefined is empty string', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString(null, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(undefined, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBe('');
        expect(dtr.ErrorMessage).toBeUndefined();
        expect(dtr.NotFound).toBeUndefined();
    });
    test('TimeOfDayHMSLookupKey with values other than Date, null or undefined are errors', () => {
        let la = new IntlLocalizationAdapter('en');
        la.RegisterBuiltInLookupKeyFunctions();
        let dtr = la.ToString({}, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString('', TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();
        dtr = la.ToString(10, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();    
        dtr = la.ToString(true, TimeOfDayHMSLookupKey);
        expect(dtr).not.toBeNull();
        expect(dtr.Value).toBeUndefined();
        expect(dtr.ErrorMessage).toBe('Not a date');
        expect(dtr.NotFound).toBeUndefined();        
    });        
});