/**
 * {@inheritDoc jivs-engine/Services/Types/IAutoGenerateDataTypeCheckService!IAutoGenerateDataTypeCheckService:interface }
 * @module jivs-engine/Services/Types/IAutoGenerateDataTypeCheckService
 */

import { ICondition } from './Conditions';
import { IDataTypeCheckGenerator } from './DataTypeCheckGenerator';
import { IDataTypeService } from './DataTypes';
import { IFieldValueHost } from './FieldValueHost';
import { IServicesAccessor } from './Services';

/**
 * Service that supports automatic generation of Conditions for the Data Type Check
 * using {@link jivs-engine/DataTypes/Types/IDataTypeCheckGenerator!IDataTypeCheckGenerator | IDataTypeCheckGenerator} instances.
 * This feature is specific to FieldValueHosts as it utilizes both the text value and native Value.
 */
export interface IAutoGenerateDataTypeCheckService extends
    IDataTypeService<IDataTypeCheckGenerator>, IServicesAccessor {
    
    /**
     * When true, data type check conditions are auto generated if not 
     * supplied in the ValueHost's list of validators.
     * Defaults to true.
     */
    enabled: boolean;
    
    /**
     * Works together with IDataTypeCheckGenerator to attempt to supply one or more 
     * Conditions suitable for the given data type lookup key that is used as a Data Type Check
     * against the native value.
     * 
     * By default, automatic generation uses the DataTypeCheckCondition. If you implement
     * an IDataTypeCheckGenerator class, you may return multiple conditions. In that case, 
     * return a DataTypeCheckCondition too if it is needed.
     * 
     * That condition determines an error when FieldValueHost.getValue() returns undefined,
     * which is a result of a conversion from text to the native value has failed.
     * 
     * There are other ways to check a data type. Strings with a well 
     * defined pattern will often be the same as they were between
     * Text Value and Native Value, aside from trimming spaces.
     * So the Native Value is a string that will need to be checked against
     * a regular expression or some other rule that confirms the string matches requirements.
     * 
     * Thats when you create a IDataTypeCheckGenerator class and register it with
     * autoGenerateDataTypeCheckService.
     * 
     * @param dataTypeLookupKey 
     * @param valueHost
     * @returns The list of Conditions generated by a matching IDataTypeCheckGenerator,
     * or a DataTypeCheckCondition if no IDataTypeCheckGenerator was found. If DataTypeCheckGenerator
     * returns an empty array, it means do not generate the DataTypeCheckCondition and this function
     * returns the empty array itself.
     */
    autoGenerateDataTypeConditions(valueHost: IFieldValueHost, dataTypeLookupKey: string): Array<ICondition>;

    /**
     * Finds the first {@link jivs-engine/DataTypes/Types/IDataTypeCheckGenerator!IDataTypeCheckGenerator | IDataTypeCheckGenerator}
     * that supports the value, or null if none are found.
     * @param dataTypeLookupKey 
     * @returns 
     */
    find(dataTypeLookupKey: string): IDataTypeCheckGenerator | null; 
}


