/**
 * {@inheritDoc jivs-engine/Services/Types/IDataTypeCheckGeneratorService!IDataTypeCheckGeneratorService:interface }
 * @module jivs-engine/Services/Types/IDataTypeCheckGeneratorService
 */

import { ConditionConfig, ICondition } from './Conditions';
import { IDataTypeCheckGenerator } from './DataTypeCheckGenerator';
import { IDataTypeService } from './DataTypes';
import { IFieldValueHost } from './FieldValueHost';
import { IServicesAccessor } from './Services';

/**
 * Service that supports automatic generation of Conditions for the Data Type Check
 * using {@link jivs-engine/DataTypes/Types/IDataTypeCheckGenerator!IDataTypeCheckGenerator | IDataTypeCheckGenerator} instances.
 * This feature is specific to FieldValueHosts as it utilizes both the text value and native Value.
 */
export interface IDataTypeCheckGeneratorService extends
    IDataTypeService<IDataTypeCheckGenerator>, IServicesAccessor {
    
    /**
     * When true, data type check conditions are auto generated if not 
     * supplied in the ValueHost's list of validators.
     * Defaults to true.
     */
    enabled: boolean;
    
    /**
     * Works together with IDataTypeCheckGenerator to attempt to supply one or more 
     * Conditions suitable for the given data type lookup key that is used as a Data Type Check
     * against the native value.
     * 
     * By default, automatic generation uses the DataTypeCheckCondition. If you implement
     * an IDataTypeCheckGenerator class, you may return multiple conditions. In that case, 
     * return a DataTypeCheckCondition too if it is needed.
     * 
     * That condition determines an error when FieldValueHost.getValue() returns undefined,
     * which is a result of a conversion from text to the native value has failed.
     * 
     * There are other ways to check a data type. Strings with a well 
     * defined pattern will often be the same as they were between
     * Text Value and Native Value, aside from trimming spaces.
     * So the Native Value is a string that will need to be checked against
     * a regular expression or some other rule that confirms the string matches requirements.
     * 
     * Thats when you create a IDataTypeCheckGenerator class and register it with
     * dataTypeCheckGeneratorService.
     * 
     * @param dataTypeLookupKey 
     * @param valueHost
     * @returns The list of Conditions generated by a matching IDataTypeCheckGenerator,
     * or a DataTypeCheckCondition if no IDataTypeCheckGenerator was found. If DataTypeCheckGenerator
     * returns an empty array, it means do not generate the DataTypeCheckCondition and this function
     * returns the empty array itself.
     */
    autoGenerateDataTypeConditions(valueHost: IFieldValueHost, dataTypeLookupKey: string): Array<ICondition>;

    /**
     * Finds the first {@link jivs-engine/DataTypes/Types/IDataTypeCheckGenerator!IDataTypeCheckGenerator | IDataTypeCheckGenerator}
     * that supports the value, or null if none are found.
     * @param dataTypeLookupKey 
     * @returns 
     */
    find(dataTypeLookupKey: string): IDataTypeCheckGenerator | null; 

    /**
     * Registers a lookup key with the corresponding data used to create an IDataTypeCheckGenerator.
     * This allows the service to automatically generate data type check conditions for the specified lookup key.
     * 
     * @param lookupKey The data type lookup key to register the generator for.
     * @param data - Behavior depends on the input:
     *  - regexp - uses a RegExpCondition internally. If you intend to exactly match the entire string,
     *    always enclose the pattern in ^ and $ to match the entire string.
     *    If you prefer case insensitive matching, include the 'i' flag in the RegExp.
     *  - array of strings - Perform a case sensitive match against each string until one matches.
     *    Internally uses a RegExpCondition.
     *  - array of ConditionConfigs (each must have conditionType property assigned) creates
     *    all of those conditions plus DataTypeCheckCondition.
     */
    registerLookupKey(lookupKey: string, data: RegExp | Array<string> | Array<ConditionConfig>,
        addDataTypeCheckCondition: boolean
    ): void;
}


