
// Example: Introduce a new Condition class, including support for fluent syntax
// Our class will require even numbers. There is already a base class for numbers,
// NumberConditionBase, but we'll ignore it in favor of showing code in the evaluate function.

// Here are the activities for creating a Condition class.
// 1. Choose a name, usually with the suffix "Condition".
// 2. Define its ConditionType, which is a string that is different from existing ConditionTypes.
// 3. Create your Configuration object interface, inheriting from an existing Configuration.
// 4. Create your class, inheriting from an existing Condition class.
// 5. Extend the fluent syntax by subclassing our standard ValidatorBuilder
//    and ConditionBuilder
// 6. Register new classes with the ValidationServices object in createValidationServices.
//    - Condition class in the ValidationServices.conditionFactory
//    - IDataTypeCheckGenerator subclass in ValidationServices.autoGenerateDataTypeCheckService
//    - ValidatorBuilder and ConditionBuilder subclasses in
//      ValidationServices.fluentFactory.
// 7. Write unit tests. See the companion file in the Tests folder.

import { OneValueConditionBase, OneValueConditionBaseConfig } from "@plblum/jivs-engine/build/Conditions/OneValueConditionBase";
import { LookupKey } from "@plblum/jivs-engine/build/DataTypes/LookupKeys";
import { ConditionEvaluateResult, ConditionCategory } from "@plblum/jivs-engine/build/Interfaces/Conditions";
import { IValidationServices } from '@plblum/jivs-engine/build/Interfaces/ValidationServices';
import { IValueHost } from "@plblum/jivs-engine/build/Interfaces/ValueHost";
import { IValueHostsManager } from "@plblum/jivs-engine/build/Interfaces/ValueHostsManager";
import { ConditionFactory } from '@plblum/jivs-engine/build/Conditions/ConditionFactory';
import { ValidatorBuilder } from "@plblum/jivs-engine/build/Builder/ValidatorBuilder";
import { ConditionBuilder } from "@plblum/jivs-engine/build/Builder/ConditionBuilder";
import { FluentValidatorConfig } from "@plblum/jivs-engine/build/Builder/Fluent";
import {
    IBuilderConfigHost, CompleteConfigBuilderHandler,
    IValidatorBuilder, IConditionBuilder
} from "@plblum/jivs-engine/build/Interfaces/ChildBuilders";
import { FieldValueHostConfig } from "@plblum/jivs-engine/build/Interfaces/FieldValueHost";

export const evenNumberConditionType = 'EvenNumber';    // we'll extend Jivs ConditionType enum with this

export interface EvenNumberConditionConfig extends OneValueConditionBaseConfig
{
}
/**
 * Condition requires an integer that is even to match. An integer that is odd does not match.
 * Any other value, including a decimal number is Undetermined.
 */
export class EvenNumberCondition extends OneValueConditionBase<EvenNumberConditionConfig>
{
    public evaluate(valueHost: IValueHost | null, valueHostsManager: IValueHostsManager): ConditionEvaluateResult | Promise<ConditionEvaluateResult> {
        valueHost = this.ensurePrimaryValueHost(valueHost, valueHostsManager);
        let value = valueHost.getValue();
        //#region  --- start optional lines
        // Give it the ability to get a number from an object that has a converter for a number.
        if (typeof value !== 'number') {
            value = valueHostsManager.services.dataTypeConverterService.convertUntilResult(value, null, LookupKey.Number);
            if (typeof value !== 'number')
                return ConditionEvaluateResult.Undetermined;
        }
        //#endregion  --- end optional lines

        if (value === Math.trunc(value))    // must be an integer
            return value % 2 === 0 ?
                ConditionEvaluateResult.Match :
                ConditionEvaluateResult.NoMatch;            
        
        return ConditionEvaluateResult.Undetermined;
    }
    protected get defaultCategory(): ConditionCategory {
        return ConditionCategory.Comparison;
    }
}

// export interface IEvenNumberConditionBuilder extends IConditionBuilder {

//     evenNumber(): void;
// }


//#region Fluent syntax
// Fluent: Subclass ConditionBuilder and add your condition functions.
export class EvenNumberConditionBuilder
    extends ConditionBuilder
 //   implements IEvenNumberConditionBuilder
{

    public evenNumber(): void {
        let config: Partial<EvenNumberConditionConfig> =
        {
            conditionType: evenNumberConditionType
        };
        this.setConfig(config as any);
    }
}
// export interface IEvenNumberValidatorBuilder extends IValidatorBuilder {
//     evenNumber(
//         errorMessage?: string | null,
//         summaryMessage?: string | null): IValidatorBuilder;
//     evenNumber(
//         validatorParameters: FluentValidatorConfig): IValidatorBuilder;
// }
// Fluent: Subclass ValidatorBuilder and add your validator functions. This requires 2 overloads.

export class EvenNumberValidatorBuilder
    extends ValidatorBuilder
//    implements IEvenNumberValidatorBuilder
{
    public evenNumber(
        errorMessage?: string | null, 
        summaryMessage?: string | null): IValidatorBuilder;
    public evenNumber(
        validatorParameters: FluentValidatorConfig): IValidatorBuilder;
    public evenNumber(
        arg2?: FluentValidatorConfig | string | null,
        arg3?: string | null): IValidatorBuilder {
        let { errorMessage, summaryMessage, conditionConfig, validatorParameters } =
            this.resolveOverloadArgs<EvenNumberConditionConfig>(arg2, arg3);
        let conditionBuilder = this.createConditionBuilder();
        conditionBuilder.evenNumber();
        return this.finish(conditionBuilder,
            errorMessage, summaryMessage, validatorParameters);
    }
}

// TypeScript Declaration Merging with ValidatorBuilder and ConditionBuilder
// This gives you intellisense and strong typing without heavy lifting
declare module "@plblum/jivs-engine/build/Interfaces/ChildBuilders"
{
    export interface IValidatorBuilder {
        evenNumber(
            errorMessage?: string | null,
            summaryMessage?: string | null): IValidatorBuilder;
        evenNumber(
            validatorParameters: FluentValidatorConfig): IValidatorBuilder;
    }
}
declare module "@plblum/jivs-engine/build/Interfaces/ChildBuilders"
{
    export interface IConditionBuilder {
        evenNumber(): void;
    }
}
//#endregion Fluent syntax

// Register after you have a ValidationService instance. Setup only on the ValidationService
export function registerEvenNumberCondition(validationServices: IValidationServices): void
{
    let cf = validationServices.conditionFactory as ConditionFactory;
    // or move just this line into registerDataTypeCheckGenerators() function     
    cf.register<EvenNumberConditionConfig>(evenNumberConditionType, (config) => new EvenNumberCondition(config));
    
    // Adding custom conditions to ValidatorBuilder and ConditionBuilder
    let ff = validationServices.fluentFactory;
    ff.setValidatorBuilderCreator((parentConfig: FieldValueHostConfig) => {
        return new EvenNumberValidatorBuilder(validationServices, parentConfig) as unknown as IValidatorBuilder;
    });
    ff.setConditionBuilderCreator((parentBuilder: IBuilderConfigHost<object>, completed?: CompleteConfigBuilderHandler<any>) => {
        return new EvenNumberConditionBuilder(validationServices, parentBuilder, completed) as unknown as IConditionBuilder;
    });        
}

