import { FieldPresentationBase } from '../FieldPresentations/FieldPresentationBase';
import { jivsErrorMessagesContainerClass } from './IssuesFoundDisplayBase';
import { TemplatedIssuesFoundDisplay, TemplatedIssuesFoundDisplayOptions } from './TemplatedIssuesFoundDisplay';

/**
 * Uses the TemplatedIssuesFoundDisplay as the base class for generating issue displays with templates.
 * Provides a way to build fixed templates for issue displays.
 * 
 * Its structure is only defined as an outer HTML tag, and the inner content is generated by the subclass.
 * It expects the subclass to use the tokens: {Header}, {Footer}, and {IssuesFound} to
 * consume the data provided in the header and footer sections, and IssuesFound data supplied.
 */
export abstract class GeneratedTemplatedIssuesFoundDisplayBase extends TemplatedIssuesFoundDisplay
{
    /**
     * Constructor for the generated templated issues found display.
     * @param options The options for configuring the generated templated issues found display.
     */
    constructor(options?: GeneratedTemplatedIssuesFoundDisplayBaseOptions)
    {
        super('', options);
        let outerClasses = FieldPresentationBase.toStyleClassNameArray(options?.outerClasses)
        this.gatherOuterClasses(outerClasses);
        this._outerClasses = outerClasses;
    }

    /**
     * Lets the subclass modify or add to the list of outer CSS classes
     * to provide a standard set of CSS classes for the outer container element.
     * @param list 
     */
    protected gatherOuterClasses(list: string[]): void
    {
    }

    /**
     * Gets the style classes for the outer element.
     */
    protected get outerClasses(): string[]
    {
        return this._outerClasses;
    }
    private _outerClasses: string[];

    protected get outerTag(): string
    {
        return 'div';
    }
    protected get outerBeginTag(): string
    {
        let outer = '';
        if (this.outerClasses.length > 0) {
            outer = ` class="${this.outerClasses.join(' ')}"`;
        }
        return `<${this.outerTag}${outer}>`;
    }

    /**
     * Generates the complete HTML template including the outer container and inner content.
     * @returns The generated HTML template as a string.
     */
    protected override generateTemplate(): string
    {
        return `${this.outerBeginTag}${this.generateTemplateContent()}</${this.outerTag}>`;
    }

    /**
     * Generates the content for the HTML template.
     */
    protected abstract generateTemplateContent(): string;

    /**
     * Utility for generateTemplateContent to include a tag with the {IssuesFound} token.
     * @returns The HTML string containing the {IssuesFound} token within a div.
     */
    protected defaultIssuesFoundHtml(): string
    {
        return `<div class="${ jivsErrorMessagesContainerClass }">{IssuesFound}</div>`;
    } 

}

export interface GeneratedTemplatedIssuesFoundDisplayBaseOptions extends Omit<TemplatedIssuesFoundDisplayOptions, 'template'>
{
    /**
     * The outer CSS classes to be applied to the outer container element. 
     * It can be a single class as a string or an array of class names.
     */
    outerClasses?: string[] | string;
}