/**
 * @inheritDoc DataTypes/ConcreteClasses/DataTypeServices!
 * @module DataTypes/Interfaces
 */

import { LookupKey } from '../DataTypes/LookupKeys';
import { ICondition, IConditionFactory } from './Conditions';
import { IInputValueHost } from './InputValueHost';
import { IServicesAccessor } from './ValidationServices';

/**
 * Partial representation of DataTypeServices for systems that
 * only use its Format feature.
 */
export interface ICoreDataTypeServices
{

/**
 * Converts the native value to a string that can be shown to the user.
 * Result includes the successfully converted value
 * or validation error information.
 * Formatting uses localization. It uses IDataTypeFormatter classes,
 * which may handle multiple cultures. When searching for a formatter,
 * it tries the ValidationServices.activeCultureID first and if no formatter
 * is supplied for that culture, it has a chain of fallback cultures that you supply
 * in the constructor.
 * @param value
 * @param lookupKey - If not supplied, a lookup key is created based on the native value type.
 * If you need alternative formatting or are supporting a user defined type,
 * always pass in the associated lookup key. They can be found in the LookupKeys module.
 * @returns successfully converted value or validation error information.
 */    
    format(value: any, lookupKey?: string | null): DataTypeResolution<string>;
}

export interface IDataTypeServices extends ICoreDataTypeServices, IServicesAccessor
{
/**
 * {@inheritDoc DataTypes/ConcreteClasses/DataTypeServices!DataTypeServices.compareValues}
 */    
    compareValues(value1: any, value2: any, lookupKey1: string | null, lookupKey2: string | null): ComparersResult;
    
/**
 * When a value is supplied without a DataType Lookup Key, this resolves the
 * DataType Lookup Key. By default, it supports values of type number, boolean,
 * string and Date object.
 * You can add your own data types by implementing IDataTypeIdentifier
 * and registered you class with the DataTypeServices.
 * @param value 
 */
    identifyLookupKey(value: any): string | null;    

/**
 * Works together with IDataTypeCheckGenerator to attempt to supply an ICondition
 * suitable for the given data type lookup key that is used as a Data Type Check
 * against the native value.
 * 
 * By default, automatic generation uses the DataTypeCheckCondition.
 * 
 * That condition determines an error when ValueHost.NativeValue is undefined,
 * which is a result of a conversion of InputValue fails.
 * 
 * There are other ways to check a data type. Strings with a well 
 * defined pattern will often be the same as they were between
 * InputValue and NativeValue, aside from trimming spaces.
 * So the NativeValue is a string that will need to be checked against
 * a regular expression or some other rule that confirms the string matches requirements.
 * 
 * Thats when you create a IDataTypeCheckGenerator class and register it with
 * DataTypeServices.
 * 
 * @param dataTypeLookupKey 
 * @param valueHost
 * @returns The Condition generated by a matching IDataTypeCheckGenerator,
 * or a DataTypeCheckCondition if none was generated. If DataTypeCheckGenerator
 * returns a null, it means do not generate the DataTypeCheckCondition and this function
 * returns null itself.
 */    
    autoGenerateDataTypeCondition(valueHost: IInputValueHost, dataTypeLookupKey: LookupKey | string): ICondition | null;
/**
 * When true, data type check conditions are auto generated if not 
 * supplied in the ValueHost's list of validators.
 * Defaults to true.
 */
    autoGenerateDataTypeConditionEnabled: boolean;
}

/**
 * Result from a method that can deliver either a value or an error in
 * attempting to generate that value.
 */
export interface DataTypeResolution<T>
{
    /**
     * If assigned, it is the resolved value.
     * If undefined, the value failed to resolve and the errorMessage is setup.
     */
    value?: T;
    /**
     * If assigned, the value failed to resolve and this is a description of what happened.
     */
    errorMessage?: string;
}


/**
 * Provides a way to associate any value with a datatype lookupkey based on its actual datatype.
 * This interface is implemented for number as "Number", Date as "Date",
 * Boolean as "Boolean", and String as "String".
 * Each instance is registered with the DataTypeServices using the 
 * RegisterDataType.
 */
export interface IDataTypeIdentifier
{
/**
 * The unique lookup key you will use to identify this native data type.
 */    
    dataTypeLookupKey: string;
/**
 * Determines if the value is identified as a match and maps to DataTypeLookupKey.
 * @param value 
 */
    supportsValue(value: any): boolean;
}

/**
 * Provides a way to include non-standard types in comparison Conditions
 * by taking the value in its non-standard type form and returning
 * another value that is either a primitive type or Date that already
 * has support by Conditions.
 * Consider these cases:
 * - A TimeSpan class represents a duration in days, hours, minutes and seconds.
 *   Use a Converter to return the total number of seconds.
 * - A RelativeDate class represents a Date calculated offset from Today
 *   by a number of days, weeks, months, and years. 
 *   Use a Converter to return a Date object with the realized date.
 * You can have several converters for the same non-standard type.
 * The Data Type Lookup key supplied on the ValueHost can be used to pick a specific one.
 */
export interface IDataTypeConverter
{
/**
 * Will be called to see if the value and DataType Lookup Key should be handled
 * by this class.
 * If the dataTypeLookupKey is null or '', evaluate the value itself,
 * such as checking its class (using 'instanceof') or for properties of an interface
 * that you are using.
 * Don't look for valid data within the object. The convert() function is responsible
 * for reporting invalid data in supported values.
 * @param value
 * @param dataTypeLookupKey
 * @returns true when its own convert() method should handle the value.
  */
    supportsValue(value: any, dataTypeLookupKey: LookupKey | string | null): boolean;
/**
 * Return the value representing the original value, but in the new data type,
 * specified by the generic T.
 * Return null if the value represents null.
 * Return undefined if the value was unconvertable.
 * @param value 
 * @param dataTypeLookupKey 
 */
    convert(value: any, dataTypeLookupKey: LookupKey | string): number | Date | string | null | undefined;
}

/**
 * Class that compares two values to determine equality, less than, greater than.
 * Create classes for each data type that doesn't support the
 * ==, !=, <, > operators the desired way.
 * However, first consider using an IDataTypeConverter to convert
 * your data type into an integer, string, or date. Those will
 * be supported by the default comparer.
 * 
 * Register your class with the DataTypeServices.
 */
export interface IDataTypeComparer
{
    supportsValues(value1: any, value2: any): boolean;

    compare(value1: any, value2: any): ComparersResult;
}

export enum ComparersResult {
    Equals,
    NotEquals,
    LessThan,
    GreaterThan,
    Undetermined
}

/**
 * Provides conversion between a native type and its formatted and localized string 
 * representation. Each is associated with a lookup key.
 * For example, the Date object has several of these implementations.
 * LookupKey="Date" provides a localized short date pattern through DateFormatter.
 * LookupKey="AbbrevDate" provides the same but in abbreviated date pattern through AbbrevDateFormatter.
 * Create implementations for each dataTypeLookupKey that needs localized formatting.
 * If you need access to ValidationServices, such as for text localization, implement
 * IServicesAccessor on your class.
 */
export interface IDataTypeFormatter
{
    /**
     * Evaluates the parameters to determine if its format() method should handle the value
     * with those same parameters.
     * It should always match the DataTypeLookupKey. 
     * It does not have to evaluate the cultureID, as there are implementations
     * where the format() function handles every culture or isn't
     * using culture at all.
     * @param dataTypeLookupKey 
     * @param cultureId - Such as 'en-US' and 'en'
     * @returns Use its format() method when true. Do not use format() when false.
     */
    supports(dataTypeLookupKey: LookupKey | string, cultureId: string): boolean;

    /**
     * Creates a formatted string for the value, applying the goals of the DataTypeLookupKey
     * and making it culture specific.
     * @param value 
     * @param dataTypeLookupKey 
     * @param cultureId 
     */
    format(value: any, dataTypeLookupKey: LookupKey | string, cultureId: string): DataTypeResolution<string>;
}

/**
 * Used to automatically generate a Condition used for Data Type Check
 * based on the DataTypeLookupKey.
 * 
 * By default, automatic generation uses the DataTypeCheckCondition.
 * 
 * That condition determines an error when ValueHost.NativeValue is undefined,
 * which is a result of a conversion of InputValue fails.
 * 
 * There are other ways to check a data type. Strings with a well 
 * defined pattern will often be the same as they were between
 * InputValue and NativeValue, aside from trimming spaces.
 * So the NativeValue is a string that will need to be checked against
 * a regular expression or some other rule that confirms the string matches requirements.
 * 
 * Thats when you create one of these and register it with
 * DataTypeServices.
 * 
 * You can also prevent autogeneration for a given dataTypeLookupKey by
 * returning null instead of a condition in CreateCondition.
 */
export interface IDataTypeCheckGenerator
{

/**
 * Determines if the dataTypeLookupKey is supported.
 * Only call CreateCondition when this returns true.
 * @param dataTypeLookupKey
 * @returns when true, datatypeLookupKey is supported and CreateCondition can be used.
 */
    supportsValue(dataTypeLookupKey: LookupKey | string): boolean;
/**
 * Creates a Condition based on the DataTypeLookupKey that will handle the Data Type Check feature.
 * Most of the time, ICondition.ConditionCategory should be DataTypeCheck.
 * @param valueHost 
 * @param dataTypeLookupKey 
 * @param conditionFactory
 * @returns A Condition instance to use or null to block auto-generation.
 */
    createCondition(valueHost: IInputValueHost, dataTypeLookupKey: LookupKey | string,
        conditionFactory: IConditionFactory): ICondition | null;
}