/**
 * @module jivs-engine/Services/ConcreteClasses/AutoGenerateDataTypeCheckService
 */

import { DataTypeCheckConditionConfig } from '../Conditions/ConcreteConditions';
import { ConditionType } from '../Conditions/ConditionTypes';
import { ConditionConfig, ICondition } from '../Interfaces/Conditions';
import { IDataTypeCheckGenerator } from '../Interfaces/DataTypeCheckGenerator';
import { IAutoGenerateDataTypeCheckService } from '../Interfaces/AutoGenerateDataTypeCheckService';
import { assertNotNull } from '../Utilities/ErrorHandling';
import { DataTypeServiceBase } from './DataTypeServiceBase';
import { IFieldValueHost } from '../Interfaces/FieldValueHost';
import { LogDetails, LoggingCategory, LoggingLevel } from '../Interfaces/LoggerService';
import { valueForLog } from '../Utilities/Utilities';

/**
 * A service that supports automatic generation of 
 * Conditions for the Data Type Check
 * using {@link jivs-engine/DataTypes/Types/IDataTypeCheckGenerator!IDataTypeCheckGenerator | IDataTypeCheckGenerator} instances.
 * 
 * This class is available on {@link jivs-engine/Services/ConcreteClasses/JivsServices!JivsServices#autoGenerateDataTypeCheckService | JivsServices.autoGenerateDataTypeCheckService}.
 * This feature is specific to FieldValueHosts as it utilizes both the Text and Native Values.
 */
export class AutoGenerateDataTypeCheckService extends DataTypeServiceBase<IDataTypeCheckGenerator>
    implements IAutoGenerateDataTypeCheckService
{
    protected indexOfExisting(item: IDataTypeCheckGenerator): number {
        return -1; // does not support replacing registered items
    }
    /**
     * When true, data type check conditions are auto generated if not 
     * supplied in the ValueHost's list of validators.
     * Defaults to true.
     */
    public get enabled(): boolean
    {
        return this._autoGenerateDataTypeConditionEnabled;
    }
    public set enabled(value: boolean)
    {
        this._autoGenerateDataTypeConditionEnabled = value;
    }
    private _autoGenerateDataTypeConditionEnabled: boolean = true;
    
    /**
     * {@inheritDoc jivs-engine/Services/Types/IAutoGenerateDataTypeCheckService!IAutoGenerateDataTypeCheckService#autoGenerateDataTypeConditions }
     */    
    public autoGenerateDataTypeConditions(valueHost: IFieldValueHost, dataTypeLookupKey: string): Array<ICondition>
    {
        let result: Array<ICondition> = [];
        try {
            assertNotNull(valueHost, 'valueHost');
            assertNotNull(dataTypeLookupKey, 'dataTypeLookupKey');
            const generator = this.find(dataTypeLookupKey);
            if (generator !== null) {
                this.logger.message(LoggingLevel.Debug, () => `Using ${valueForLog(generator)}`);
                result = generator.createConditions(valueHost, dataTypeLookupKey, this.services.conditionFactory); // may return null
                return result;
            }
            const config = this.createDefaultConditionConfig(valueHost);
            const condition = this.services.conditionFactory.create(config);
            result.push(condition);
            return result;
        }
        finally
        {
            this.logger.log(LoggingLevel.Info, () => {
                const details: LogDetails = {
                    category: LoggingCategory.Result,
                    message: null!
                };
                if (result.length > 0)
                {
                    const conditionNames = result.map((c) => c.conditionType).join('; ');
                    details.message = `Auto generated: ${conditionNames}`;
                }
                else
                    details.message = 'Nothing to auto generate';
                return details;
            });            
        }
    }
    protected createDefaultConditionConfig(valueHost: IFieldValueHost): ConditionConfig
    {
        return {
            conditionType: ConditionType.DataTypeCheck,
            valueHostName: valueHost.getName()
        } as DataTypeCheckConditionConfig;
    }

    /**
     * Finds the first {@link jivs-engine/DataTypes/Types/IDataTypeCheckGenerator!IDataTypeCheckGenerator | IDataTypeCheckGenerator}
     * that supports the value, or null if none are found.
     * Runs the lazyloader if setup and the first search fails.
     * @param dataTypeLookupKey 
     * @returns 
     */
    public find(dataTypeLookupKey: string): IDataTypeCheckGenerator | null {
        let result = this.getAll().find((dtg) => dtg.supportsValue(dataTypeLookupKey)) ?? null;
        if (result === null && this.ensureLazyLoaded())
            result = this.find(dataTypeLookupKey);
        return result;        
    }

}