/**
 * @module jivs-engine/Services/ConcreteClasses/DataTypeCheckGeneratorService
 */

import { DataTypeCheckConditionConfig } from '../Conditions/ConcreteConditions';
import { ConditionType } from '../Conditions/ConditionTypes';
import { ConditionConfig, ICondition } from '../Interfaces/Conditions';
import { IDataTypeCheckGenerator } from '../Interfaces/DataTypeCheckGenerator';
import { IDataTypeCheckGeneratorService } from '../Interfaces/DataTypeCheckGeneratorService';
import { assertNotNull, CodingError } from '../Utilities/ErrorHandling';
import { DataTypeServiceBase } from './DataTypeServiceBase';
import { IFieldValueHost } from '../Interfaces/FieldValueHost';
import { LogDetails, LoggingCategory, LoggingLevel } from '../Interfaces/LoggingService';
import { valueForLog } from '../Utilities/Utilities';
import { ListOfConditionsDataTypeCheckGenerator, RegExpDataTypeCheckGenerator } from '../DataTypes/DataTypeCheckGenerators';

/**
 * A service that supports automatic generation of 
 * Conditions for the Data Type Check
 * using {@link jivs-engine/DataTypes/Types/IDataTypeCheckGenerator!IDataTypeCheckGenerator | IDataTypeCheckGenerator} instances.
 * 
 * This class is available on {@link jivs-engine/Services/ConcreteClasses/JivsServices!JivsServices#dataTypeCheckGeneratorService | JivsServices.dataTypeCheckGeneratorService}.
 * This feature is specific to FieldValueHosts as it utilizes both the Text and Native Values.
 */
export class DataTypeCheckGeneratorService extends DataTypeServiceBase<IDataTypeCheckGenerator>
    implements IDataTypeCheckGeneratorService
{
    protected indexOfExisting(item: IDataTypeCheckGenerator): number {
        return -1; // does not support replacing registered items
    }
    /**
     * When true, data type check conditions are auto generated if not 
     * supplied in the ValueHost's list of validators.
     * Defaults to true.
     */
    public get enabled(): boolean
    {
        return this._autoGenerateDataTypeConditionEnabled;
    }
    public set enabled(value: boolean)
    {
        this._autoGenerateDataTypeConditionEnabled = value;
    }
    private _autoGenerateDataTypeConditionEnabled: boolean = true;
    
    /**
     * {@inheritDoc jivs-engine/Services/Types/IDataTypeCheckGeneratorService!IDataTypeCheckGeneratorService#autoGenerateDataTypeConditions }
     */    
    public autoGenerateDataTypeConditions(valueHost: IFieldValueHost, dataTypeLookupKey: string): Array<ICondition>
    {
        let result: Array<ICondition> = [];
        try {
            assertNotNull(valueHost, 'valueHost');
            assertNotNull(dataTypeLookupKey, 'dataTypeLookupKey');
            const generator = this.find(dataTypeLookupKey);
            if (generator !== null) {
                this.logger.message(LoggingLevel.Debug, () => `Using ${valueForLog(generator)}`);
                result = generator.createConditions(valueHost, dataTypeLookupKey, this.services.conditionFactory); // may return null
                return result;
            }
            const config = this.createDefaultConditionConfig(valueHost);
            const condition = this.services.conditionFactory.create(config);
            result.push(condition);
            return result;
        }
        finally
        {
            this.logger.log(LoggingLevel.Info, () => {
                const details: LogDetails = {
                    category: LoggingCategory.Result,
                    message: null!
                };
                if (result.length > 0)
                {
                    const conditionNames = result.map((c) => c.conditionType).join('; ');
                    details.message = `Auto generated: ${conditionNames}`;
                }
                else
                    details.message = 'Nothing to auto generate';
                return details;
            });            
        }
    }
    protected createDefaultConditionConfig(valueHost: IFieldValueHost): ConditionConfig
    {
        return {
            conditionType: ConditionType.DataTypeCheck,
            valueHostName: valueHost.getName()
        } as DataTypeCheckConditionConfig;
    }

    /**
     * Finds the first {@link jivs-engine/DataTypes/Types/IDataTypeCheckGenerator!IDataTypeCheckGenerator | IDataTypeCheckGenerator}
     * that supports the value, or null if none are found.
     * Runs the lazyloader if setup and the first search fails.
     * @param dataTypeLookupKey 
     * @returns 
     */
    public find(dataTypeLookupKey: string): IDataTypeCheckGenerator | null {
        let result = this.getAll().find((dtg) => dtg.supportsValue(dataTypeLookupKey)) ?? null;
        if (result === null && this.ensureLazyLoaded())
            result = this.find(dataTypeLookupKey);
        return result;        
    }
    /**
     * Registers a lookup key with the corresponding data used to create an IDataTypeCheckGenerator.
     * This allows the service to automatically generate data type check conditions for the specified lookup key.
     * 
     * This is a great way to quickly add your own enumerated types and strings with strong pattern
     * types (like Email). The result is that types you introduce automatically get a validator
     * performing a data type check like this:
     * ```ts
     * const emailLookupKey = 'Email';
     * dataTypeCheckGeneratorService.registerLookupKey(emailLookupKey, /^[^\s@]+@[^\s@]+\.[^\s@]+$/);
     * ```
     * Now use the Builder:
     * ```ts
     * builder.field('emailAddress', emailLookupKey); // this now has a RegExpCondition auto-assigned
     * ```
     * 
     * @param lookupKey The data type lookup key to register the generator for. Usually you have created 
     * a Lookup Key for your own type, like 'Email' or 'MyEnumType'.
     * @param data - Behavior depends on the input:
     *  - regexp - uses a RegExpCondition internally. If you intend to exactly match the entire string,
     *    always enclose the pattern in ^ and $ to match the entire string.
     *    If you prefer case insensitive matching, include the 'i' flag in the RegExp.
     *  - array of strings - Perform a case sensitive match against each string until one matches.
     *    Internally uses a RegExpCondition.
     *  - array of ConditionConfigs (each must have conditionType property assigned) creates
     *    all of those conditions plus DataTypeCheckCondition.
     * @param addDataTypeCheckCondition - Whether to add a DataTypeCheckCondition along 
     * with the generated conditions. Defaults to true.
     */
    public registerLookupKey(lookupKey: string, data: RegExp | Array<string> | Array<ConditionConfig>,
        addDataTypeCheckCondition: boolean = true
    ): void
    {
        assertNotNull(lookupKey, 'lookupKey');
        assertNotNull(data, 'data');
        if (data instanceof RegExp)
        {
            this.register(new RegExpDataTypeCheckGenerator(lookupKey, data, addDataTypeCheckCondition));
            return;
        }
        else if (Array.isArray(data))
        {
            if (typeof data[0] === 'string')
            {
                this.register(new RegExpDataTypeCheckGenerator(lookupKey, data as Array<string>, addDataTypeCheckCondition));
                return;
            }
            else if (typeof data[0] === 'object' && 'conditionType' in data[0])
            {
                this.register(new ListOfConditionsDataTypeCheckGenerator(lookupKey, data as Array<ConditionConfig>, addDataTypeCheckCondition));
                return;
            }

        }

        throw new CodingError('Unsupported data type for registerLookupKey');
    }
}