import { RegExpCondition, RegExpConditionConfig } from "../../src/Conditions/ConcreteConditions";
import { ConditionFactory } from "../../src/Conditions/ConditionFactory";
import { ConditionType } from "../../src/Conditions/ConditionTypes";
import { CurrencyFormatter } from '../../src/DataTypes/DataTypeFormatters';
import { LookupKey } from "../../src/DataTypes/LookupKeys";
import
    {
        ConditionCategory, ConditionConfig,
        ICondition, IConditionFactory
    } from "../../src/Interfaces/Conditions";
import { IDataTypeCheckGenerator } from "../../src/Interfaces/DataTypeCheckGenerator";
import { IDataTypeParser } from "../../src/Interfaces/DataTypeParsers";
import { DataTypeResolution } from "../../src/Interfaces/DataTypes";
import
    {
        FieldValueHostConfig, FieldValueHostInstanceState, FieldValueHostSetValueOptions,
        IFieldValueHost, IFieldValueHostCallbacks, toIFieldValueHostCallbacks
    } from "../../src/Interfaces/FieldValueHost";
import { LoggingCategory, LoggingLevel } from "../../src/Interfaces/LoggerService";
import { IValidatableValueHostBase, ValueHostValidationState } from "../../src/Interfaces/ValidatableValueHostBase";
import
    {
        IssueFound,
        ValidateOptions,
        ValidationSeverity,
        ValidationStatus,
        ValueHostValidateResult
    } from "../../src/Interfaces/Validation";
import { IValueHostsManager, ValueHostsManagerConfig } from "../../src/Interfaces/ValueHostsManager";
import { IJivsServices } from "../../src/Interfaces/JivsServices";
import { IValidator, ValidatorConfig } from "../../src/Interfaces/Validator";
import
    {
        IValueHost, SetValueOptions, ValidTypesForInstanceStateStorage,
        ValueHostConfig, ValueHostInstanceState
    } from "../../src/Interfaces/ValueHost";
import { ValueHostType } from "../../src/Interfaces/ValueHostFactory";
import { IValueHostResolver } from "../../src/Interfaces/ValueHostResolver";
import { AutoGenerateDataTypeCheckService } from "../../src/Services/AutoGenerateDataTypeCheckService";
import { ConsoleLoggerService } from "../../src/Services/ConsoleLoggerService";
import { TextLocalizerService } from "../../src/Services/TextLocalizerService";
import { CapturingLogger } from "../../src/Support/CapturingLogger";
import { AlwaysMatchesConditionType, NeverMatchesConditionType, UserSuppliedResultConditionType } from "../../src/Support/conditionsForTesting";
import { createJivsServicesForTesting, registerDataTypeParsers } from "../../src/Support/createJivsServicesForTesting";
import { CodingError } from "../../src/Utilities/ErrorHandling";
import { ValueHostsManager } from "../../src/Validation/ValueHostsManager";
import { CalcValueHost } from "../../src/ValueHosts/CalcValueHost";
import { FieldValueHost, FieldValueHostGenerator, toIFieldValueHost } from "../../src/ValueHosts/FieldValueHost";
import { StaticValueHost } from '../../src/ValueHosts/StaticValueHost';
import { MockValueHostsManager, MockJivsServices } from "../TestSupport/mocks";
import { InjectedError } from '../../src/Interfaces/ValidatorsValueHostBase';
import { IDataTypeFormatter } from '../../src/Interfaces/DataTypeFormatters';


interface ITestSetupConfig {
    services: MockJivsServices,
    valueHostsManager: MockValueHostsManager,
    config: FieldValueHostConfig,
    state: FieldValueHostInstanceState,
    valueHost: FieldValueHost
};

function createFieldValueHostConfig(fieldNumber: number = 1,
    dataType: string = LookupKey.String,
    initialValue?: any): FieldValueHostConfig {
    return {
        name: 'Field' + fieldNumber,
        label: 'Label' + fieldNumber,
        valueHostType: ValueHostType.Field,
        dataType: dataType,
        initialValue: initialValue,
        validatorConfigs: []
    };
}

function finishPartialFieldValueHostConfig(partialConfig: Partial<FieldValueHostConfig> | null):
    FieldValueHostConfig {
    let defaultIVH = createFieldValueHostConfig(1, LookupKey.String);
    if (partialConfig) {
        return { ...defaultIVH, ...partialConfig };
    }
    return defaultIVH;
}

function finishPartialFieldValueHostConfigs(partialConfigs: Array<Partial<FieldValueHostConfig>> | null):
    Array<FieldValueHostConfig> | null {
    let result: Array<FieldValueHostConfig> = [];
    if (partialConfigs) {
        for (let i = 0; i < partialConfigs.length; i++) {
            let vhd = partialConfigs[i];
            result.push(finishPartialFieldValueHostConfig(vhd));
        }
    }

    return result;
}


function createValidatorConfig(condConfig: ConditionConfig | null): ValidatorConfig {
    return {
        conditionConfig: condConfig,
        errorMessage: 'Local',
        summaryMessage: 'Summary',
    };
}
function finishPartialValidatorConfig(validatorConfig: Partial<ValidatorConfig> | null):
    ValidatorConfig {
    let defaultIVD = createValidatorConfig(null);
    if (validatorConfig) {
        return { ...defaultIVD, ...validatorConfig };
    }
    return defaultIVD;
}

function finishPartialValidatorConfigs(validatorConfigs: Array<Partial<ValidatorConfig>> | null):
    Array<ValidatorConfig> {
    let result: Array<ValidatorConfig> = [];
    if (validatorConfigs) {
        let defaultIVD = createValidatorConfig(null);
        for (let i = 0; i < validatorConfigs.length; i++) {
            let vd = validatorConfigs[i];
            result.push(finishPartialValidatorConfig(vd));
        }
    }

    return result;
}

function createFieldValueHostInstanceState(fieldNumber: number = 1): FieldValueHostInstanceState {
    return {
        name: 'Field' + fieldNumber,
        value: undefined,
        textValue: undefined,
        issuesFound: null,
        status: ValidationStatus.NotAttempted
    };
}
function finishPartialFieldValueHostInstanceState(partialState: Partial<FieldValueHostInstanceState> | null): FieldValueHostInstanceState {
    let defaultIVS = createFieldValueHostInstanceState(1);
    if (partialState) {
        return { ...defaultIVS, ...partialState };
    }
    return defaultIVS;
}

/**
 * Returns an ValueHost (PublicifiedValueHost subclass) ready for testing.
 * @param partialIVHConfig - Provide just the properties that you want to test.
 * Any not supplied but are required will be assigned using these rules:
 * name: 'Field1',
 * label: 'Label1',
 * valueHostType: 'Field',
 * DataType: LookupKey.String,
 * InitialValue: 'DATA'
 * validatorConfigs: []
 * @param partialState - Use the default state by passing null. Otherwise pass
 * a state. Your state will override default values. To avoid overriding,
 * pass the property with a value of undefined.
 * These are the default values
 * name: 'Field1'
 * Value: undefined
 * TextValue: undefined
 * IssuesFound: null,
 * ValidationStatus: NotAttempted
 * @returns An object with all of the parts that were setup including 
 * ValueHostsManager, Services, ValueHosts, the complete Config,
 * and the state.
 */
function setupFieldValueHost(
    partialIVHConfig?: Partial<FieldValueHostConfig> | null,
    partialState?: Partial<FieldValueHostInstanceState> | null): ITestSetupConfig {
    let services = new MockJivsServices(true, true);
    (services.loggerService as CapturingLogger).chainedLogger = new ConsoleLoggerService(services.loggerService.minLevel);
    (services.loggerService as CapturingLogger).overrideMinLevelWhen({ hasData: true });
    let vhm = new MockValueHostsManager(services);
    let updatedConfig = finishPartialFieldValueHostConfig(partialIVHConfig ?? null);
    let updatedState = finishPartialFieldValueHostInstanceState(partialState ?? null);

    let vh = vhm.addFieldValueHostWithConfig(updatedConfig, updatedState);
    //new FieldValueHost(vhm, updatedConfig, updatedState);
    return {
        services: services,
        valueHostsManager: vhm,
        config: updatedConfig,
        state: updatedState,
        valueHost: vh as FieldValueHost
    };
}

/**
 * Creates a configuration where you can call validate() and test various results.
 * @param partialValidatorConfigs - Always provide a list of the validatorConfigs in the desired order.
 * If null, no validators are made available to validate
 * @param partialFieldValueState - Use to supply initial TextValue and Value properties. Any property
 * not supplied will be provided.
 * @returns Configuration that has been setup. Use valueHost to invoke validation functions.
 */
function setupFieldValueHostForValidate(
    partialValidatorConfigs: Array<Partial<ValidatorConfig>> | null,
    partialFieldValueState: Partial<FieldValueHostInstanceState> | null,
    vhGroup?: string | null): ITestSetupConfig {

    let fieldValueConfig: Partial<FieldValueHostConfig> = {
        validatorConfigs: partialValidatorConfigs ?
            finishPartialValidatorConfigs(partialValidatorConfigs) :
            undefined
    };
    if (vhGroup !== undefined)
        fieldValueConfig.group = vhGroup;

    let updatedState = finishPartialFieldValueHostInstanceState(
        { ...{ textValue: '' }, ...partialFieldValueState });

    return setupFieldValueHost(fieldValueConfig, updatedState);
}

describe('constructor and resulting property values', () => {

    test('constructor with valid parameters created and sets up Services, Config, and InstanceState', () => {
        let services = new MockJivsServices(true, true);
        let vhm = new MockValueHostsManager(services);
        let testItem: FieldValueHost | null = null;
        expect(()=> testItem = new FieldValueHost(vhm, {
            name: 'Field1',
            valueHostType: ValueHostType.Field,
            validatorConfigs: []
            },
            {
                name: 'Field1',
                status: ValidationStatus.NotAttempted,
                issuesFound: null,
                value: undefined
            })).not.toThrow();

        expect(testItem!.valueHostsManager).toBe(vhm);

        expect(testItem!.getName()).toBe('Field1');
        expect(testItem!.getPropertyName()).toBe('Field1');
        expect(testItem!.getLabel()).toBe('');
        expect(testItem!.getDataType()).toBeNull();
        expect(testItem!.getValue()).toBeUndefined();
        expect(testItem!.isChanged).toBe(false);
        expect(testItem!.isValid).toBe(true);
        expect(testItem!.asyncProcessing).toBe(false);
        expect(testItem!.corrected).toBe(false);        
        expect(testItem!.required).toBe(false);
        expect(testItem!.getInjectedError()).toBeNull();
        expect(testItem!.getParserLookupKey()).toBeUndefined();
    });

    test('constructor with Config.propertyName sets up getPropertyName correctly', () => {
        let services = new MockJivsServices(true, true);
        let vhm = new MockValueHostsManager(services);
        let testItem: FieldValueHost | null = null;
        expect(()=> testItem = new FieldValueHost(vhm, {
            name: 'Field1',
            propertyName: 'Prop1',
            valueHostType: ValueHostType.Field,
            validatorConfigs: []
            },
            {
                name: 'Field1',
                status: ValidationStatus.NotAttempted,
                issuesFound: null,
                value: undefined
            })).not.toThrow();

        expect(testItem!.valueHostsManager).toBe(vhm);

        expect(testItem!.getName()).toBe('Field1');
        expect(testItem!.getPropertyName()).toBe('Prop1');

    });    
});

describe('setValue', () =>
{
    test('Value was changed. OnValueChanged called. (confirm ancestor was not broken)', () => {
        let setup = setupFieldValueHost();
        let testItem = setup.valueHost;

        let callbackInvoked = 0;
        setup.valueHostsManager.onValueChanged = (valueHost, oldValue) => {
            callbackInvoked++;
        };
        testItem.setValue(100);
        expect(callbackInvoked).toBe(1);

    });

    test('Value was changed. OnValueHostInstanceStateChanged called.(confirm ancestor was not broken) ', () => {
        const initialValue = 100;

        let setup = setupFieldValueHost();
        let callbackInvoked = 0;
        setup.valueHostsManager.onValueHostInstanceStateChanged = (valueHost, stateToRetain) => {
            callbackInvoked++;
        };        
        let testItem = setup.valueHost;
        testItem.setValue(initialValue);

        expect(callbackInvoked).toBe(1);
    });

});
describe('FieldValueHost.getTextValue', () => {
    test('Set instanceState.TextValue to undefined; getTextValue is undefined', () => {
        let setup = setupFieldValueHost(null, {
            textValue: undefined
        });
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NotAttempted);
        let value: any = null;
        expect(() => value = setup.valueHost.getTextValue()).not.toThrow();
        expect(value).toBeUndefined();
    });
    test('Set instanceState.TextValue to "abc"; getTextValue is "abc"', () => {
        let setup = setupFieldValueHost(null, {
            textValue: 'abc'
        });
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NotAttempted);
        let value: any = null;
        expect(() => value = setup.valueHost.getTextValue()).not.toThrow();
        expect(value).toBe('abc');
    });

});

describe('setTextValue with getTextValue to check result', () => {
    function testWithoutValidation(textValue: any,
        options: FieldValueHostSetValueOptions| null | undefined): void
    {
        let setup = setupFieldValueHost();
//        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        setup.services.dataTypeParserService.enabled = false;

        expect(() => setup.valueHost.setTextValue(textValue, options!)).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NeedsValidation);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getTextValue()).toBe(textValue);
        let changes = setup.valueHostsManager.getHostStateChanges();
        expect(changes.length).toBe(1);
        expect((<FieldValueHostInstanceState>changes[0]).textValue).toBe(textValue);
        expect((<FieldValueHostInstanceState>changes[0]).changeCounter).toBe(1);        
    }
    test('Value of "ABC", options is undefined. Sets value to "ABC" and does not validate. IsChanged is true', () => {
        testWithoutValidation("ABC", undefined);
    });
    test('Value of "ABC", options is empty object. Sets value to "ABC" and does not validate', () => {
        testWithoutValidation("ABC", {});
    });
    test('Value of "ABC", options is null. Sets value to "ABC" and does not validate', () => {
        testWithoutValidation("ABC", null);
    });
    test('Value of "ABC", options is { validate: false }. Sets value to "ABC" and does not validate', () => {
        testWithoutValidation("ABC", { validate: false });
    });
    test('Value of "ABC", options is { validate: true }. Sets value to "ABC" and validate (no Validators to cause Invalid, so result is Undetermined)', () => {
        let setup = setupFieldValueHost();
        setup.services.dataTypeParserService.enabled = false;

        expect(() => setup.valueHost.setTextValue("ABC", { validate: true })).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.Undetermined);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getTextValue()).toBe("ABC");
        let changes = setup.valueHostsManager.getHostStateChanges();
        expect(changes.length).toBe(2); // first changes the value; second changes ValidationStatus
        let valueChange = <FieldValueHostInstanceState>changes[0];
        expect(valueChange.textValue).toBe("ABC");
        let vrChange = <FieldValueHostInstanceState>changes[1];
        expect(vrChange.status).toBe(ValidationStatus.Undetermined);
        expect(vrChange.changeCounter).toBe(1);
    });
    // with onTextValueChanged callback, the callback is called when the text value changes. The callback is not called when the text value does not change.
    test('with onTextValueChanged callback, the callback is called when the text value changes', () =>
    {
        let setup = setupFieldValueHost();
        setup.services.dataTypeParserService.enabled = false;
        let valueHostsCaptured: Array<FieldValueHost> = [];
        setup.valueHostsManager.onTextValueChanged = (valueHost, oldValue) =>
        {
            valueHostsCaptured.push(valueHost as FieldValueHost);
        }
        expect(() => setup.valueHost.setTextValue("ABC", { validate: true })).not.toThrow();
        expect(valueHostsCaptured.length).toBe(1);
        expect(valueHostsCaptured[0].getValue()).toBeUndefined();
        expect(valueHostsCaptured[0].getTextValue()).toBe("ABC");
    });
    // same but with onValueChanged set, it does not get called
    test('with onValueChanged callback, the callback is not called when the text value changes', () =>
    {
        let setup = setupFieldValueHost();
        setup.services.dataTypeParserService.enabled = false;
        let valueHostsCaptured: Array<FieldValueHost> = [];
        setup.valueHostsManager.onValueChanged = (valueHost, oldValue) =>
        {
            valueHostsCaptured.push(valueHost as FieldValueHost);
        }
        expect(() => setup.valueHost.setTextValue("ABC", { validate: true })).not.toThrow();
        expect(valueHostsCaptured.length).toBe(0);
    });
    test('Before calling, validate for ValidationStatus=Undetermined. Set value to 10 with options { Reset: true }. Expect value to be 20, IsChanged = false, and ValidationStatus to NotAttempted', () => {
        let setup = setupFieldValueHost();
        setup.services.dataTypeParserService.enabled = false;

        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NotAttempted);
        setup.valueHost.validate();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.Undetermined);
        expect(() => setup.valueHost.setTextValue('ABC', { reset: true })).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NotAttempted);
        expect(setup.valueHost.getIssuesFound()).toBeNull();
        expect(setup.valueHost.isChanged).toBe(false);
    });

    describe('setTextValue with options to test injectedError', () =>
    {
        test('injectedError supplied and is saved in state when value is assigned', () =>
        {
            let setup = setupFieldValueHost();
            setup.services.dataTypeParserService.enabled = false;

            expect(() => setup.valueHost.setTextValue("ABC", { injectedError: { errorMessage: 'ERROR' } })).not.toThrow();
            expect(setup.valueHost.getInjectedError()).toEqual({ errorMessage: 'ERROR' });
            expect(setup.valueHost.getValue()).toBeUndefined();
            expect(setup.valueHost.getTextValue()).toBe("ABC");
        });
        test('injectedError supplied in setTextValue and then setValue without it does not retain it', () =>
        {
            let setup = setupFieldValueHost();
            setup.services.dataTypeParserService.enabled = false;
            expect(() => setup.valueHost.setTextValue("ABC", { injectedError: { errorMessage: 'ERROR' } })).not.toThrow();
            setup.valueHost.setValue('ABC');
            expect(setup.valueHost.getInjectedError()).toBeNull();
        });
        test('injectedError supplied in state using setValueToUndefined', () =>
        {
            let setup = setupFieldValueHost();
            setup.services.dataTypeParserService.enabled = false;

            setup.valueHost.setValueToUndefined({ injectedError: { errorMessage: 'ERROR' } });
            expect(setup.valueHost.getInjectedError()).toEqual({ errorMessage: 'ERROR' });
        });
    });    
    test('Log call when Level=Debug.', () => {
        const initialValue = 'A';
        const finalValue = 'B';
        let setup = setupFieldValueHost({}, { value: initialValue } );
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        let testItem = setup.valueHost;
        testItem.setTextValue(finalValue);
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('setTextValue\\("B"\\)', LoggingLevel.Debug, null)).toBeTruthy();
    });
    test('isEnabled=false will not change the value.', () => {
        const initialValue = 'A';   // this is the native value
        const finalValue = 'B';
        let setup = setupFieldValueHost({}, { value: initialValue } );
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        let testItem = setup.valueHost;
        testItem.setEnabled(false);
        testItem.setTextValue(finalValue);
        expect(testItem.getTextValue()).toBeUndefined();   // never set it
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('ValueHost "Field1" disabled.', LoggingLevel.Warn, null)).toBeTruthy();
        expect(logger.findMessage('overrideDisabled', LoggingLevel.Info, null)).toBeNull();
    });
    test('isEnabled=false will change the value when option.overrideDisabled=true.', () => {
        const initialValue = 'A';
        const finalValue = 'B';
        let setup = setupFieldValueHost({}, { value: initialValue } );
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        let testItem = setup.valueHost;
        testItem.setEnabled(false);
        testItem.setTextValue(finalValue, { overrideDisabled: true });
        expect(testItem.getTextValue()).toBe(finalValue);
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('overrideDisabled', LoggingLevel.Info, null)).toBeTruthy();
        expect(logger.findMessage('ValueHost "Field1" disabled.', LoggingLevel.Warn, null)).toBeNull();
    });    
});
describe('setTextValue with parserLookupKey enabled to see both text value and native values are assigned', () => {
    function testWithParser(textValue: any,
        nativeDataTypeLookupKey: string,
        parserLookupKey: string | null | undefined,
        options: FieldValueHostSetValueOptions| null | undefined,
        expectedNativeValue: any,
        expectParserCreatorToBeCalled: boolean = false
        ): ITestSetupConfig
    {
        let ivh: FieldValueHostConfig = {
            name: 'Field1',
            validatorConfigs: [],
            dataType: nativeDataTypeLookupKey,
            parserLookupKey: parserLookupKey
        }
        let setup = setupFieldValueHost(ivh);
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        registerDataTypeParsers(setup.services.dataTypeParserService);
        setup.services.lookupKeyFallbackService.register(LookupKey.Integer, LookupKey.Number);

        expect(() => setup.valueHost.setTextValue(textValue, options!)).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NeedsValidation);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getTextValue()).toBe(textValue);
        expect(setup.valueHost.getValue()).toBe(expectedNativeValue);     
        expect(setup.valueHost.getInjectedError()).toBeNull();
        expect(setup.valueHost.getParserLookupKey()).toBe(parserLookupKey);
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('Attempt to parse into native value', LoggingLevel.Debug,    
            null)).toBeTruthy();  
        expect(logger.findMessage('Parsed into native value', LoggingLevel.Debug,    
            null, { hasData: true })).toBeTruthy();
        if (expectParserCreatorToBeCalled)
            expect(logger.findMessage('Parsing', LoggingLevel.Info,    
                null)).toBeTruthy();
        return setup;
    }
    function testWithParserWithErrorMessage(textValue: any,
        nativeDataTypeLookupKey: string,
        parserLookupKey: string | null | undefined,
        options: FieldValueHostSetValueOptions| null | undefined
        ): ITestSetupConfig
    {
        let ivh: FieldValueHostConfig = {
            name: 'Field1',
            validatorConfigs: [],
            dataType: nativeDataTypeLookupKey,
            parserLookupKey: parserLookupKey
        }
        let setup = setupFieldValueHost(ivh);
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
 //       (setup.services.loggerService as CapturingLogger).
        registerDataTypeParsers(setup.services.dataTypeParserService);
        setup.services.lookupKeyFallbackService.register(LookupKey.Integer, LookupKey.Number);

        expect(() => setup.valueHost.setTextValue(textValue, options!)).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NeedsValidation);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getTextValue()).toBe(textValue);
        expect(setup.valueHost.getValue()).toBeUndefined();     
        expect(setup.valueHost.getInjectedError()).toBeTruthy();
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('Attempt to parse into native value', LoggingLevel.Debug,    
            null)).toBeTruthy();  
        expect(logger.findMessage('Parser reported error', LoggingLevel.Debug,    
            null, { hasData: true })).toBeTruthy();  

        return setup;
    }    

    function testWithDisabledParser(textValue: any,
        nativeDataTypeLookupKey: string,
        parserLookupKey: string | null | undefined, // when null, no parser
        options: FieldValueHostSetValueOptions | null | undefined,    // when disableParser = true
        errorMsg: string | null, // the message to find in the log
        isActiveParser: boolean = true  // when false, no parser
        ): ITestSetupConfig
    {
        let ivh: FieldValueHostConfig = {
            name: 'Field1',
            validatorConfigs: [],
            dataType: nativeDataTypeLookupKey,
            parserLookupKey: parserLookupKey
        }
        let setup = setupFieldValueHost(ivh);
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        setup.services.dataTypeParserService.enabled = isActiveParser;
        registerDataTypeParsers(setup.services.dataTypeParserService);
        setup.services.lookupKeyFallbackService.register(LookupKey.Integer, LookupKey.Number);

        expect(() => setup.valueHost.setTextValue(textValue, options!)).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NeedsValidation);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getTextValue()).toBe(textValue);    
        expect(setup.valueHost.getInjectedError()).toBeNull();
        if (errorMsg)
            expect(logger.findMessage(errorMsg, LoggingLevel.Debug,
                null)).toBeTruthy();
        return setup;
    }    


    test('As a string with dataType=string, expecting to parse and update native value. The parser will be CleanupStringParser set only to trim. This parser does not encounter any errors', () => {
        testWithParser('ABC', LookupKey.String, undefined, {}, 'ABC');
        testWithParser(' ABC ', LookupKey.String, undefined, {}, 'ABC');     
        testWithParser('ABC', LookupKey.String, LookupKey.String, {}, 'ABC');     
        testWithParser('ABC', null!, LookupKey.String, {}, 'ABC');         
        testWithParser('ABC', undefined!, LookupKey.String, {}, 'ABC');     
        testWithParser('ABC', undefined!, LookupKey.String, { disableParser: false}, 'ABC');           
      
    });
    test('As a string representing a number with dataType=number, expecting to parse and update native value. None will generate errors', () => {
        testWithParser('10', LookupKey.Number, undefined, {}, 10);
        testWithParser(' 20 ', LookupKey.Number, undefined, {}, 20);     
        testWithParser('30', LookupKey.Number, LookupKey.Number, {}, 30);        
        testWithParser('30', null!, LookupKey.Number, {}, 30);           
        testWithParser('30', undefined!, LookupKey.Number, {}, 30);                
        testWithParser('30', undefined!, LookupKey.Number, { disableParser: false }, 30);

    });
    test('As a string representing a number with dataType=integer, expecting to parse using fallback lookupkey and update native value. None will generate errors', () => {
        testWithParser('10', LookupKey.Integer, undefined, {}, 10);
        testWithParser(' 20 ', LookupKey.Integer, undefined, {}, 20);     
        testWithParser('30', null!, LookupKey.Integer, {}, 30);        
        testWithParser('30', undefined!, LookupKey.Integer, {}, 30);

    });    

    test('As a string that cannot parse to a number, but using datatype=number, reports an error', () => {
        testWithParserWithErrorMessage('ABC', LookupKey.Number, undefined, {});
        testWithParserWithErrorMessage('ABC', undefined!, LookupKey.Number, {});
        testWithParserWithErrorMessage('ABC', LookupKey.Integer, undefined, {});
        testWithParserWithErrorMessage('ABC', undefined!, LookupKey.Integer, {});       
    });

    test('parserLookupKey = null disables parsing, resulting in just updating text value but no change to native value', () => {
        testWithDisabledParser('ABC', LookupKey.String, null, {}, 'parserLookupKey=null');   // parserLookupKey = null
    });

    test('option.disableParser=true disables parsing, resulting in just updating text value but no change to native value', () => {
        testWithDisabledParser('ABC', LookupKey.String, undefined, { disableParser: true }, 'option.disableParser=true');
    });   
    test('option.duringEdit=true disables parsing, resulting in just updating text value but no change to native value', () => {
        testWithDisabledParser('ABC', LookupKey.String, undefined, { duringEdit: true }, null);
    });        
    test('dataTypeParserService.enabled=false disables parsing, resulting in just updating text value but no change to native value', () => {
        testWithDisabledParser('ABC', LookupKey.String, null, { }, null, false);  // parserservice disabled
    });    
    test('value is not a string disables parsing, resulting in just updating text value but no change to native value', () => {
        testWithDisabledParser(10, LookupKey.Number, undefined, {}, null); // not a string
        testWithDisabledParser(false, LookupKey.Number, undefined, {}, null); // not a string
        testWithDisabledParser(new Date(), LookupKey.Number, undefined, {}, null); // not a string
    });    

    class TestWithExceptionParser implements IDataTypeParser<string> {
        supports(dataTypeLookupKey: string, cultureId: string, text: string): boolean
        {
            return true;
        }
        isCompatible(dataTypeLookupKey: string, cultureId: string): boolean
        {
            return true;
        }
        parse(text: string, dataTypeLookupKey: string, cultureId: string): DataTypeResolution<string | null>
        {
            throw new CodingError('EXCEPTION');
        }

    };
    test('Parser throws', () => {  
        let ivh: FieldValueHostConfig = {
            name: 'Field1',
            validatorConfigs: [],
            dataType: LookupKey.Number,
            parserLookupKey: 'TESTWITHEXCEPTION'
        };
        let setup = setupFieldValueHost(ivh);
        setup.services.loggerService.minLevel = LoggingLevel.Debug;

        setup.services.dataTypeParserService.register(new TestWithExceptionParser());
        const errorMsg = 'EXCEPTION';
        let regex = new RegExp(errorMsg);
        expect(() => setup.valueHost.setTextValue('Test')).toThrow(regex);
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NotAttempted);
        expect(setup.valueHost.isChanged).toBe(false);
        expect(setup.valueHost.getTextValue()).toBeUndefined();
        expect(setup.valueHost.getValue()).toBeUndefined();
        expect(setup.valueHost.getInjectedError()).toBeNull();
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('Attempt to parse into native value', LoggingLevel.Debug,
            null)).toBeTruthy();
        expect(logger.findMessage(errorMsg, LoggingLevel.Error,
            LoggingCategory.Exception)).toBeTruthy();        
    });
});

describe('FieldValueHost.setValues with getTextValue and getValue to check result', () => {
    test('Text value of "10", Value of 10, options is undefined. Sets both values, IsChanged = true, and does not validate', () => {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(10, "10")).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NeedsValidation);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getValue()).toBe(10);
        expect(setup.valueHost.getTextValue()).toBe("10");
        let changes = setup.valueHostsManager.getHostStateChanges();
        expect(changes.length).toBe(1);
        expect((<FieldValueHostInstanceState>changes[0]).value).toBe(10);
        expect((<FieldValueHostInstanceState>changes[0]).textValue).toBe("10");
        expect((<FieldValueHostInstanceState>changes[0]).changeCounter).toBe(1);
        expect(setup.valueHost.getInjectedError()).toBeNull();
    });
    test('Text value of "10", Value of 10, options is empty object. Sets both values, IsChanged = true, and does not validate', () => {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(10, "10", {})).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NeedsValidation);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getValue()).toBe(10);
        expect(setup.valueHost.getTextValue()).toBe("10");
        let changes = setup.valueHostsManager.getHostStateChanges();
        expect(changes.length).toBe(1);
        expect((<FieldValueHostInstanceState>changes[0]).value).toBe(10);
        expect((<FieldValueHostInstanceState>changes[0]).textValue).toBe("10");
        expect((<FieldValueHostInstanceState>changes[0]).changeCounter).toBe(1);
    });
    test('Text value of "10", Value of 10, options is null. Sets both values, IsChanged = true, and does not validate', () => {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(10, "10", null!)).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NeedsValidation);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getValue()).toBe(10);
        expect(setup.valueHost.getTextValue()).toBe("10");
        let changes = setup.valueHostsManager.getHostStateChanges();
        expect(changes.length).toBe(1);
        expect((<FieldValueHostInstanceState>changes[0]).value).toBe(10);
        expect((<FieldValueHostInstanceState>changes[0]).textValue).toBe("10");
        expect((<FieldValueHostInstanceState>changes[0]).changeCounter).toBe(1);
    });
    test('Text value of "10", Value of 10, options is { validate: false }. Sets both values, IsChanged = true, and does not validate', () => {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(10, "10", { validate: false })).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.NeedsValidation);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getValue()).toBe(10);
        expect(setup.valueHost.getTextValue()).toBe("10");
        let changes = setup.valueHostsManager.getHostStateChanges();
        expect(changes.length).toBe(1);
        expect((<FieldValueHostInstanceState>changes[0]).value).toBe(10);
        expect((<FieldValueHostInstanceState>changes[0]).textValue).toBe("10");
        expect((<FieldValueHostInstanceState>changes[0]).changeCounter).toBe(1);
    });
    test('Text value of "10", Value of 10, options is { validate: true }. Sets both values, IsChanged = true, and validate (no Validators to cause Invalid, so result is Undetermined)', () => {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(10, "10", { validate: true })).not.toThrow();
        expect(setup.valueHost.validationStatus).toBe(ValidationStatus.Undetermined);
        expect(setup.valueHost.isChanged).toBe(true);
        expect(setup.valueHost.getValue()).toBe(10);
        expect(setup.valueHost.getTextValue()).toBe("10");
        let changes = setup.valueHostsManager.getHostStateChanges();
        expect(changes.length).toBe(2); // first changes the value; second changes ValidationStatus
        let valueChange = <FieldValueHostInstanceState>changes[0];
        expect(valueChange.value).toBe(10);
        expect(valueChange.textValue).toBe("10");
        let vrChange = <FieldValueHostInstanceState>changes[1];
        expect(vrChange.status).toBe(ValidationStatus.Undetermined);
        expect(vrChange.changeCounter).toBe(1);
    });
    // Calls both onValueChanged and onTextValueChanged callbacks when both are set. The callbacks are called when the value changes. The callbacks are not called when the value does not change.
    test('Calls both onValueChanged and onTextValueChanged callbacks when both are set', () =>
    {
        let setup = setupFieldValueHost();
        let valueChangedHosts: Array<FieldValueHost> = [];
        setup.valueHostsManager.onValueChanged = (valueHost, oldValue) =>
        {
            valueChangedHosts.push(valueHost as FieldValueHost);
        }
        let textValueChangedHosts: Array<FieldValueHost> = [];
        setup.valueHostsManager.onTextValueChanged = (valueHost, oldValue) =>
        {
            textValueChangedHosts.push(valueHost as FieldValueHost);
        }
        expect(() => setup.valueHost.setValues(10, "10", { validate: true })).not.toThrow();
        expect(valueChangedHosts.length).toBe(1);
        expect(valueChangedHosts[0].getValue()).toBe(10);
        expect(valueChangedHosts[0].getTextValue()).toBe("10");
        expect(textValueChangedHosts[0].getValue()).toBe(10);
        expect(textValueChangedHosts[0].getTextValue()).toBe("10");
    });

    test('injectedError supplied and is saved when native value is undefined', () => {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(undefined, "ABC", { injectedError: { errorMessage: 'ERROR' } })).not.toThrow();
        expect(setup.valueHost.getInjectedError()).toEqual({ errorMessage: 'ERROR' });
        expect(setup.valueHost.isChanged).toBe(true);
    });
    test('injectedError supplied but is saved when native value is defined', () => {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(10, "10", { injectedError: { errorMessage: 'ERROR' } })).not.toThrow();
        expect(setup.valueHost.getInjectedError()).toEqual({ errorMessage: 'ERROR' });
        expect(setup.valueHost.isChanged).toBe(true);
    });
    test('injectedError supplied in first call but not in second does not have first injected error', () => {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(undefined, undefined, { injectedError: { errorMessage: 'ERROR' } })).not.toThrow();
        setup.valueHost.setValues(10, "10");
        expect(setup.valueHost.getInjectedError()).toBeNull();
    });
    test('injectedError supplied in first call but not in second does not have first injected error', () =>
    {
        let setup = setupFieldValueHost();

        expect(() => setup.valueHost.setValues(undefined, undefined, { injectedError: { errorMessage: 'ERROR' } })).not.toThrow();
        setup.valueHost.setValues(10, "10", { injectedError: { errorMessage: 'ERROR2' } });
        expect(setup.valueHost.getInjectedError()).toEqual({ errorMessage: 'ERROR2' });
    });    
    test('injectedError and Reset supplied; reset clears the error and marks as unchanged', () => {
        let setup = setupFieldValueHost();

        setup.valueHost.setValues(10, "10", { injectedError: { errorMessage: 'ERROR' }, reset: true });
        expect(setup.valueHost.getInjectedError()).toBeNull();
        expect(setup.valueHost.isChanged).toBe(false);
    });
    test('Log call when Level=Debug.', () => {
        const initialValue = 'A';
        const finalValue = 'B';
        let setup = setupFieldValueHost({}, { value: initialValue } );
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        let testItem = setup.valueHost;
        testItem.setValues(finalValue, ' B ');
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('setValues\\("B", " B "\\)', LoggingLevel.Debug, null)).toBeTruthy();
    });
    test('isEnabled=false will not change the value.', () => {
        const initialValue = 'A';
        const finalValue = 'B';
        let setup = setupFieldValueHost({}, { value: initialValue } );
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        let testItem = setup.valueHost;
        testItem.setEnabled(false);
        testItem.setValues(finalValue, " B ");
        expect(testItem.getValue()).toBe(initialValue);
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('ValueHost "Field1" disabled.', LoggingLevel.Warn, null)).toBeTruthy();
        expect(logger.findMessage('overrideDisabled', LoggingLevel.Info, null)).toBeNull();
    });
    test('isEnabled=false will change the value when option.overrideDisabled=true.', () => {
        const initialValue = 'A';
        const finalValue = 'B';
        let setup = setupFieldValueHost({}, { value: initialValue } );
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        let testItem = setup.valueHost;
        testItem.setEnabled(false);
        testItem.setValues(finalValue, " B ", { overrideDisabled: true });
        expect(testItem.getValue()).toBe(finalValue);
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('overrideDisabled', LoggingLevel.Info, null)).toBeTruthy();
        expect(logger.findMessage('ValueHost "Field1" disabled.', LoggingLevel.Warn, null)).toBeNull();
    });    
});

describe('FieldValueHost using FieldValueHostConfig.formatterLookupKey features with setValue()', () =>
{
    // setValue has been tested without any formatter options. Now to handle
    // config.formatterLookupKey.
    // When either is provided, setValue will defer to setValues(nativeValue, textValue, options)
    // and tests should confirm that both the native value and text value are set correctly.
    // Tests include logging with Level=Debug to confirm that the formatter is being used 
    // and that the text value is being set correctly.
    // setValue's options includes option.disableFormatter which when true will disable the formatter 
    // and continue using setValue().
    
    // Create some test cases
    // 1. formatterLookupKey is provided and registered, and setValue is called with a native value. Confirm that the text value is set correctly using the formatter.
    // 2. option.disableFormatter=true is provided in setValue's options, and confirm that the formatter is not used and the text value is not set.
    // 3. formatterLookupKey=null is provided in setValue's options, and confirm that the formatter is not used and the text value is not set.
    // 4. formatterLookupKey is provided but not registered, and setValue is called with a native value. Confirm that an error is thrown.
     
    test('formatterLookupKey is provided and registered, and setValue is called with a native value. Confirm that the text value is set correctly using the formatter.', () =>
    {
        // setupFieldValueHost will configure all built-in formatters, so we can use LookupKey.Number
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: LookupKey.Number
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        setup.valueHost.setValue(123);

        expect(setup.valueHost.getTextValue()).toBe('123');
        expect(setup.valueHost.getValue()).toBe(123);
        expect(logger.findMessage('Attempt to format into text value', LoggingLevel.Debug)).toBeTruthy();
        expect(logger.findMessage('Formatter used', LoggingLevel.Debug)).toBeTruthy();
    });
    test('option.disableFormatter=true is provided in setValue\'s options, and confirm that the formatter is not used and the text value is not set.', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: LookupKey.Number
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        setup.valueHost.setValue(123, <FieldValueHostSetValueOptions> { disableFormatter: true });
        expect(setup.valueHost.getTextValue()).toBeUndefined();
        expect(setup.valueHost.getValue()).toBe(123);
        expect(logger.findMessage('option.disableFormatter=true', LoggingLevel.Debug)).toBeTruthy();
    });
    test('formatterLookupKey is provided but not registered, and setValue is called with a native value. Confirm that an error is thrown.', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: 'NonExistentFormatter'
        });
        expect(() => setup.valueHost.setValue(123)).toThrow(/No DataTypeFormatter for LookupKey/);
    });
    // service.isActive() is false (DataTypeFormatterService.enabled=false), and setValue is called with a native value. Confirm that the formatter is not used and the text value is not set.
    test('service.isActive() is false (DataTypeFormatterService.enabled=false), and setValue is called with a native value. Confirm that the formatter is not used and the text value is not set.', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: LookupKey.Number
        });
        setup.services.dataTypeFormatterService.enabled = false;
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        setup.valueHost.setValue(123);
        expect(setup.valueHost.getTextValue()).toBeUndefined();
        expect(setup.valueHost.getValue()).toBe(123);
        expect(logger.findMessage('Attempt to format into text value', LoggingLevel.Debug)).toBeFalsy();
    });

    // let's focus on the ValueHostsManager.onValueChanged callback to be sure its called in the normal case
    test('ValueHostsManager.onValueChanged callback is called when setValues is called', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: LookupKey.Number
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;

        let valHostsThatChanged: Array<FieldValueHost> = [];
        setup.valueHostsManager.onValueChanged = (valueHost, validateResult) =>
        {
            valHostsThatChanged.push(valueHost as FieldValueHost);
        };
        setup.valueHost.setValue(10);

        expect(valHostsThatChanged.length).toBe(1);
        expect(valHostsThatChanged[0]).toBeInstanceOf(FieldValueHost);
        expect(valHostsThatChanged[0].getValue()).toBe(10);
        expect(valHostsThatChanged[0].getTextValue()).toBe("10");
        expect(logger.findMessage('Formatter used', LoggingLevel.Debug)).toBeTruthy();
        expect(logger.findMessage('notifyOtherValueHostsOfValueChange', LoggingLevel.Debug)).toBeTruthy();
    });
    test('ValueHostsManager.onTextValueChanged callback is called when setValues is called', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: LookupKey.Number
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        let valHostsThatTextChanged: Array<FieldValueHost> = [];
        setup.valueHostsManager.onTextValueChanged = (valueHost, validateResult) =>
        {
            valHostsThatTextChanged.push(valueHost as FieldValueHost);
        };
        setup.valueHost.setValue(10);

        expect(valHostsThatTextChanged.length).toBe(1);
        expect(valHostsThatTextChanged[0]).toBeInstanceOf(FieldValueHost);
        expect(valHostsThatTextChanged[0].getValue()).toBe(10);
        expect(valHostsThatTextChanged[0].getTextValue()).toBe("10");

        expect(logger.findMessage('Formatter used', LoggingLevel.Debug)).toBeTruthy();
        expect(logger.findMessage('notifyOtherValueHostsOfValueChange', LoggingLevel.Debug)).toBeTruthy();
    });
    test('ValueHostsManager.onValueHostValidationStateChanged callback is called when setValues is called', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: LookupKey.Number
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        let valHostsThatValidated: Array<FieldValueHost> = [];
        setup.valueHostsManager.onValueHostValidationStateChanged = (valueHost, validateResult) =>
        {
            valHostsThatValidated.push(valueHost as FieldValueHost);
        };

        setup.valueHost.setValue(10);
        expect(valHostsThatValidated.length).toBe(1);
        expect(valHostsThatValidated[0]).toBeInstanceOf(FieldValueHost);

        expect(logger.findMessage('Formatter used', LoggingLevel.Debug)).toBeTruthy();
        expect(logger.findMessage('notifyOtherValueHostsOfValueChange', LoggingLevel.Debug)).toBeTruthy();
    });
    // when formatterLookupKey=null, does not format and logs 'Did not format'
    test('when formatterLookupKey=null, does not format and logs "formatterLookupKey=null"', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: null
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;

        setup.valueHost.setValue(10);
        expect(setup.valueHost.getTextValue()).toBeUndefined();
        expect(logger.findMessage('formatterLookupKey=null', LoggingLevel.Debug)).toBeTruthy();
    });
    // both formatterLookupKey and dataType config options are undefined. Logs 'No lookupKey supplied'
    test('both formatterLookupKey and dataType config options are undefined. Logs "No lookupKey supplied"', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: undefined,
            formatterLookupKey: undefined
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        setup.valueHost.setValue(10);
        expect(setup.valueHost.getTextValue()).toBeUndefined();
        expect(logger.findMessage('No lookupKey supplied', LoggingLevel.Debug)).toBeTruthy();
    });
    class FormatterThrows implements IDataTypeFormatter
    {
        supports(dataTypeLookupKey: string, cultureId: string): boolean
        {
            return true
        }
        format(value: any, dataTypeLookupKey: string, cultureId: string): DataTypeResolution<string>
        {
            throw new CodingError('EXCEPTION');
        }
    }

    test('Formatter throws', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: 'FormatterThrows'   
        });
        setup.services.dataTypeFormatterService.register(new FormatterThrows());
        setup.services.loggerService.minLevel = LoggingLevel.Debug;
        const errorMsg = 'EXCEPTION';
        let regex = new RegExp(errorMsg);
        expect(() => setup.valueHost.setValue(10)).toThrow(regex);
        expect(setup.valueHost.getValue()).toBeUndefined();
        expect(setup.valueHost.getTextValue()).toBeUndefined();
        let logger = setup.services.loggerService as CapturingLogger;
        expect(logger.findMessage('Attempt to format into text value', LoggingLevel.Debug,
            null)).toBeTruthy();
        expect(logger.findMessage(errorMsg, LoggingLevel.Error,
            LoggingCategory.Exception)).toBeTruthy();        
    });
    // demonstrate setValues and setTextValue do not use the formatter
    test('setValues does not use the formatter', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: LookupKey.Currency    
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        setup.valueHost.setValues(10, '20');    // this text value is definitely not what the formatter would produce, but setValues does not use the formatter
        expect(setup.valueHost.getTextValue()).toBe('20');
        expect(setup.valueHost.getValue()).toBe(10);
        expect(logger.findMessage('Attempt to format into text value', LoggingLevel.Debug,
            null)).toBeNull();
    });
    test('setTextValue does not use the formatter', () =>
    {
        let setup = setupFieldValueHost({
            name: 'Field1',
            dataType: LookupKey.Number,
            formatterLookupKey: LookupKey.Currency
        });
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Debug;
        setup.valueHost.setTextValue('20');
        expect(setup.valueHost.getTextValue()).toBe('20');  // if the formatter was used, it would have been '$20.00' or similar
        expect(setup.valueHost.getValue()).toBeUndefined();
        expect(logger.findMessage('Attempt to format into text value', LoggingLevel.Debug,
            null)).toBeNull();
    });
});

describe('FieldValueHost.validate uses autogenerated DataTypeCheck condition', () => {
    test('No conditions at all. DataTypeCheckCondition gets added', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
        ];
        let state: Partial<FieldValueHostInstanceState> = {};
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Info;
        setup.services.autoGenerateDataTypeCheckService.enabled = true;
        (setup.services.textLocalizerService as TextLocalizerService).registerErrorMessage(ConditionType.DataTypeCheck, null, {
            '*': 'Error Found'
        });

        let onValStateChanged: ValueHostValidationState | null = null;
        setup.valueHostsManager.onValueHostValidationStateChanged = (valueHost, validateResult) => {
            onValStateChanged = validateResult;
        };
        setup.valueHost.setValues(undefined, 'ABC');   // will violate DataTypeCheckCondition
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                status: ValidationStatus.NeedsValidation,
                issuesFound: null,
                isValid: true,
                doNotSave: true,
                asyncProcessing: false,
                corrected: false,
            });           
        setup.valueHost.validate();
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                issuesFound: [{
                    errorCode: ConditionType.DataTypeCheck,
                    valueHostName: 'Field1',
                    severity: ValidationSeverity.Severe,    // due to DataTypeCheck
                    errorMessage: 'Error Found',
                    summaryMessage: 'Error Found',
                    doNotSave: true
                }],
                isValid: false,
                doNotSave: true,
                asyncProcessing: false,
                status: ValidationStatus.Invalid,
                corrected: false
            }
        );        

        expect(logger.findMessage('Condition for Data Type Check', LoggingLevel.Info, LoggingCategory.Result)).toBeTruthy();
    });
    test('1 condition exists and it is not a DataTypeCheck category. DataTypeCheckCondition gets added', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
            {
                conditionConfig: {
                    conditionType: AlwaysMatchesConditionType
                }
            }
        ];
        let state: Partial<FieldValueHostInstanceState> = {};
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Info;
        setup.services.autoGenerateDataTypeCheckService.enabled = true;
        (setup.services.textLocalizerService as TextLocalizerService).registerErrorMessage(ConditionType.DataTypeCheck, null, {
            '*': 'Error Found'
        });

        let onValStateChanged: ValueHostValidationState | null = null;
        setup.valueHostsManager.onValueHostValidationStateChanged = (valueHost, validateResult) => {
            onValStateChanged = validateResult;
        };
        setup.valueHost.setValues(undefined, 'ABC');   // will violate DataTypeCheckCondition
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                status: ValidationStatus.NeedsValidation,
                issuesFound: null,
                isValid: true,
                doNotSave: true,
                asyncProcessing: false,
                corrected: false,
            });           
        setup.valueHost.validate();
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                issuesFound: [{
                    errorCode: ConditionType.DataTypeCheck,
                    valueHostName: 'Field1',
                    severity: ValidationSeverity.Severe,    // due to DataTypeCheck
                    errorMessage: 'Error Found',
                    summaryMessage: 'Error Found',
                    doNotSave: true
                }],
                isValid: false,
                doNotSave: true,
                asyncProcessing: false,
                status: ValidationStatus.Invalid,
                corrected: false
            }
        );


        expect(logger.findMessage('Condition for Data Type Check', LoggingLevel.Info, LoggingCategory.Result)).toBeTruthy();
    });
    test('1 condition and it is an actual DataTypeCheckCondition. No DataTypeCheckCondition gets added.', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
            {
                conditionConfig: {
                    conditionType: ConditionType.DataTypeCheck
                },
                errorMessage: null, // so we can use TextLocalizerService
                summaryMessage: null
            }
        ];
        let state: Partial<FieldValueHostInstanceState> = {};
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Info;
        setup.services.autoGenerateDataTypeCheckService.enabled = true;
        (setup.services.textLocalizerService as TextLocalizerService).registerErrorMessage(ConditionType.DataTypeCheck, null, {
            '*': 'Error Found'
        });

        let onValStateChanged: ValueHostValidationState | null = null;
        setup.valueHostsManager.onValueHostValidationStateChanged = (valueHost, validateResult) => {
            onValStateChanged = validateResult;
        };
        setup.valueHost.setValues(undefined, 'ABC');   // will violate DataTypeCheckCondition
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                status: ValidationStatus.NeedsValidation,
                issuesFound: null,
                isValid: true,
                doNotSave: true,
                asyncProcessing: false,
                corrected: false,
            });           
        setup.valueHost.validate();
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                issuesFound: [{
                    errorCode: ConditionType.DataTypeCheck,
                    valueHostName: 'Field1',
                    severity: ValidationSeverity.Severe,
                    errorMessage: 'Error Found',
                    summaryMessage: 'Error Found',
                    doNotSave: true
                }],
                isValid: false,
                doNotSave: true,
                asyncProcessing: false,
                status: ValidationStatus.Invalid,
                corrected: false
            }
        );        

        expect(logger.findMessage('Condition for Data Type Check', LoggingLevel.Info, LoggingCategory.Configuration)).toBeNull(); // proves not auto generated
    });

    test('1 condition and it has ConditionCategory=DataTypeCheck. No DataTypeCheckCondition gets added.', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
            {
                conditionConfig: <RegExpConditionConfig>{
                    conditionType: ConditionType.RegExp,
                    expressionAsString: '^A$', // will match only "A" and we will supply "ABC"
                    category: ConditionCategory.DataTypeCheck
                },
                errorMessage: null, // so we can use TextLocalizerService
                summaryMessage: null
            }
        ];
        let state: Partial<FieldValueHostInstanceState> = {};
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        (setup.services.conditionFactory as ConditionFactory).register<RegExpConditionConfig>(
            ConditionType.RegExp, (config) => new RegExpCondition(config));
        let logger = setup.services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Info;
        setup.services.autoGenerateDataTypeCheckService.enabled = true;
        (setup.services.textLocalizerService as TextLocalizerService).registerErrorMessage(ConditionType.RegExp, null, {
            '*': 'Error Found'
        });
        let onValStateChanged: ValueHostValidationState | null = null;
        setup.valueHostsManager.onValueHostValidationStateChanged = (valueHost, validateResult) => {
            onValStateChanged = validateResult;
        };
        setup.valueHost.setValues('ABC', 'ABC');   // will violate the regexp
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                status: ValidationStatus.NeedsValidation,
                issuesFound: null,
                isValid: true,
                doNotSave: true,
                asyncProcessing: false,
                corrected: false,
            });           
        setup.valueHost.validate();
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                issuesFound: [{
                    errorCode: ConditionType.RegExp,
                    valueHostName: 'Field1',
                    severity: ValidationSeverity.Severe,    // due to regexp
                    errorMessage: 'Error Found',
                    summaryMessage: 'Error Found',
                    doNotSave: true
                }],
                isValid: false,
                doNotSave: true,
                asyncProcessing: false,
                status: ValidationStatus.Invalid,
                corrected: false
            }
        );        

        expect(logger.findMessage('Condition for Data Type Check', LoggingLevel.Info, LoggingCategory.Configuration)).toBeNull(); // proves not auto generated
    });
    test('Register a DataTypeCheckCondition for PhoneNumber and ensure it gets autogenerated and used', () => {
        const phoneNumberLookupKey = 'PhoneNumber';
        const phoneNumberConditionType = 'PhoneNumber';
        class PhoneNumberDataTypeCheckGenerator implements IDataTypeCheckGenerator {
            supportsValue(dataTypeLookupKey: string): boolean {
                return dataTypeLookupKey === phoneNumberLookupKey;
            }
            createConditions(valueHost: IFieldValueHost, dataTypeLookupKey: string, conditionFactory: IConditionFactory): Array<ICondition> {
                return [new RegExpCondition({
                    conditionType: phoneNumberConditionType,
                    expression: /^\d\d\d \d\d\d\-\d{4}$/, // ### ###-####
                    valueHostName: null
                })];
            }

        }
        let services = new MockJivsServices(true, true);
        let logger = services.loggerService as CapturingLogger;
        logger.minLevel = LoggingLevel.Info;
        services.autoGenerateDataTypeCheckService.enabled = true;
        (services.autoGenerateDataTypeCheckService as AutoGenerateDataTypeCheckService).
            register(new PhoneNumberDataTypeCheckGenerator());

        (services.textLocalizerService as TextLocalizerService).
            registerErrorMessage(phoneNumberConditionType, null,
                {
                    '*': 'Error Found'
                });

        let configs: Array<ValueHostConfig> = [
            <FieldValueHostConfig>{
                valueHostType: ValueHostType.Field,
                name: 'Field1',
                dataType: phoneNumberLookupKey,
                validatorConfigs: []
            }
        ];

        let onValStateChanged: ValueHostValidationState | null = null;        
        let vmConfig: ValueHostsManagerConfig = {
            services: services,
            valueHostConfigs: configs,
            onValueHostValidationStateChanged: (valueHost, validateResult) => {
                onValStateChanged = validateResult;
            }
        };
        let vhm = new ValueHostsManager(vmConfig);
        let vh = vhm.getValueHost('Field1') as FieldValueHost;     
        vh.setValues('ABC', 'ABC');   // will violate the regexp
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                status: ValidationStatus.NeedsValidation,
                issuesFound: null,
                isValid: true,
                doNotSave: true,
                asyncProcessing: false,
                corrected: false,
            });        
        
        vh.validate();
        expect(onValStateChanged).toEqual(
            <ValueHostValidationState>{
                issuesFound: [{
                    errorCode: phoneNumberConditionType,
                    valueHostName: 'Field1',
                    severity: ValidationSeverity.Severe, // due to regexp
                    errorMessage: 'Error Found',
                    summaryMessage: 'Error Found',
                    doNotSave: true
                }],
                isValid: false,
                doNotSave: true,
                asyncProcessing: false,
                status: ValidationStatus.Invalid,
                corrected: false
            });        

        expect(logger.findMessage('PhoneNumber Condition for Data Type Check', LoggingLevel.Info)).toBeTruthy();
    });

});

describe('FieldValueHostGenerator members', () => {
    test('CanCreate returns true for ValueHostType.Field', () => {
        let testItem = new FieldValueHostGenerator();
        expect(testItem.canCreate(<FieldValueHostConfig>{
            valueHostType: ValueHostType.Field,
            name: 'Field1',
            label: '',
            validatorConfigs: null
        })).toBe(true);
    });
    test('CanCreate returns false for unexpected type', () => {
        let testItem = new FieldValueHostGenerator();
        expect(testItem.canCreate(<FieldValueHostConfig>{
            valueHostType: 'Unexpected',
            name: 'Field1',
            label: '',
            validatorConfigs: null
        })).toBe(false);
    });

    test('CanCreate returns true for Type not defined and presence of ValidationConfig property (using null as a value)', () => {
        let testItem = new FieldValueHostGenerator();
        expect(testItem.canCreate(<any>{
            name: 'Field1',
            label: '',
            validatorConfigs: null
        })).toBe(true);
    });
    test('CanCreate returns true for Type not defined and presence of ValidationConfig property using [] as a value', () => {
        let testItem = new FieldValueHostGenerator();
        expect(testItem.canCreate(<any>{
            name: 'Field1',
            label: '',
            validatorConfigs: []
        })).toBe(true);
    });
    test('CanCreate returns false for Type not defined and lack of ValidationConfig property', () => {
        let testItem = new FieldValueHostGenerator();
        expect(testItem.canCreate(<any>{
            name: 'Field1',
            label: ''
        })).toBe(false);
    });

    test('CanCreate returns false for Type=undefined and lack of ValidationConfig property', () => {
        let testItem = new FieldValueHostGenerator();
        expect(testItem.canCreate(<any>{
            Type: undefined,
            name: 'Field1',
            label: ''
        })).toBe(false);
    });

    test('create returns instance of FieldValueHost with VM, Config and State established', () => {
        let services = new MockJivsServices(false, false);
        let vhm = new MockValueHostsManager(services);
        let config: FieldValueHostConfig = {
            name: 'Field1',
            valueHostType: ValueHostType.Field,
            label: '',
            validatorConfigs: null
        };
        let state: FieldValueHostInstanceState = {
            name: 'Field1',
            issuesFound: null,
            status: ValidationStatus.NotAttempted,
            value: undefined,
            textValue: 'TEST'
        };
        let testItem = new FieldValueHostGenerator();
        let vh: IFieldValueHost | null = null;
        expect(() => vh = testItem.create(vhm, config, state)).not.toThrow();
        expect(vh).not.toBeNull();
        expect(vh).toBeInstanceOf(FieldValueHost);
        expect(vh!.getName()).toBe(config.name);    // check Config value
        expect(vh!.getTextValue()).toBe('TEST');  // check instanceState value
    });
});
describe('FieldValueHost.required', () => {
    test('Has a RequireTextCondition. required returns true', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
            {
                conditionConfig: {
                    conditionType: ConditionType.RequireText
                }
            }
        ];
        let state: Partial<FieldValueHostInstanceState> = {
        };
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        expect(setup.valueHost.required).toBe(true);
    });
    test('Has a custom condition with Category=Require. required returns true', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
            {
                conditionConfig: {
                    conditionType: UserSuppliedResultConditionType,
                    category: ConditionCategory.Require
                }
            }
        ];
        let state: Partial<FieldValueHostInstanceState> = {
        };
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        expect(setup.valueHost.required).toBe(true);
    });    
    test('Lacks a condition with category=Require. required returns false', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
            {
                conditionConfig: {
                    conditionType: ConditionType.DataTypeCheck
                }
            }
        ];
        let state: Partial<FieldValueHostInstanceState> = {
        };
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        expect(setup.valueHost.required).toBe(false);
    });
    test('Has a RequireTextCondition but its last amongst several. required returns true', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
            {
                conditionConfig: {
                    conditionType: NeverMatchesConditionType
                }
            },
            {
                conditionConfig: {
                    conditionType: ConditionType.DataTypeCheck
                }
            },
            {
                conditionConfig: {
                    conditionType: ConditionType.RequireText
                }
            }
        ];
        let state: Partial<FieldValueHostInstanceState> = {
        };
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        expect(setup.valueHost.required).toBe(true);
    });
    test('Has a custom condition with Category=Require but its last amongst several. required returns true', () => {
        let ivConfigs: Array<Partial<ValidatorConfig>> = [
            {
                conditionConfig: {
                    conditionType: NeverMatchesConditionType
                }
            },
            {
                conditionConfig: {
                    conditionType: ConditionType.DataTypeCheck
                }
            },
            {
                conditionConfig: {
                    conditionType: UserSuppliedResultConditionType,
                    category: ConditionCategory.Require
                }
            }
        ];
        let state: Partial<FieldValueHostInstanceState> = {
        };
        let setup = setupFieldValueHostForValidate(ivConfigs, state);
        expect(setup.valueHost.required).toBe(true);
    });    
});

describe('toIFieldValueHost function', () => {
    test('Passing actual FieldValueHost matches interface returns same object.', () => {
        let vhm = new MockValueHostsManager(new MockJivsServices(false, false));
        let testItem = new FieldValueHost(vhm, {
            name: 'Field1',
            label: 'Label1',
            validatorConfigs: []
        },
            {
                name: 'Field1',
                value: undefined,
                issuesFound: null,
                status: ValidationStatus.NotAttempted,
                textValue: undefined
            });
        expect(toIFieldValueHost(testItem)).toBe(testItem);
    });
    class TestIFieldValueHostImplementation implements IFieldValueHost {
        valueHostsManager: IValueHostsManager = {} as IValueHostsManager;       
        dispose(): void { }
        groupCheck(options?: ValidateOptions | undefined): boolean {
            throw new Error("Method not implemented.");
        }
        
        gatherValueHostNames(collection: Set<string>, valueHostResolver: IValueHostResolver): void {
            throw new Error("Method not implemented.");
        }


        getTextValue(): string | undefined {
            throw new Error("Method not implemented.");
        }
        setTextValue(textValue: string | undefined, options?: SetValueOptions | undefined): void {
            throw new Error("Method not implemented.");
        }
        setValues(nativeValue: any, textValue: string | undefined, options?: SetValueOptions | undefined): void {
            throw new Error("Method not implemented.");
        }
        otherValueHostChangedNotification(valueHostIdThatChanged: string, revalidate: boolean): void {
            throw new Error("Method not implemented.");
        }
        validate(options?: ValidateOptions | undefined): ValueHostValidateResult {
            throw new Error("Method not implemented.");
        }
        clearValidation(): boolean {
            throw new Error("Method not implemented.");
        }
        isValid: boolean = true;
        validationStatus: ValidationStatus = ValidationStatus.NotAttempted;
        asyncProcessing: boolean = false;
        corrected: boolean = false;

        addExternalIssuesFound(issuesFound: IssueFound[], determinedLocally: boolean, options?: ValidateOptions | undefined): boolean {
            throw new Error("Method not implemented.");
        }
        addExternalIssueFound(issueFound: IssueFound, determinedLocally: boolean, options?: ValidateOptions | undefined): boolean {
            throw new Error("Method not implemented.");
        }        
        clearExternalIssuesFound(options?: ValidateOptions): boolean {
            throw new Error("Method not implemented.");
        }
        get doNotSave(): boolean {
            throw new Error("Method not implemented.");
        }

        get currentValidationState(): ValueHostValidationState {
            throw new Error("Method not implemented.");
        }

        getIssueFound(errorCode: string): IssueFound | null {
            throw new Error("Method not implemented.");
        }

        getIssuesFound(group?: string | undefined): IssueFound[] {
            throw new Error("Method not implemented.");
        }
        getInjectedError(): InjectedError | null
        {
            throw new Error('Method not implemented.');
        }
        setInjectedError(injectedError: InjectedError): void
        {
            throw new Error('Method not implemented.');
        }
        clearInjectedError(): void
        {
            throw new Error('Method not implemented.');
        }
        getParserLookupKey(): string | null | undefined
        {
            throw new Error("Method not implemented.");
        }        
        required: boolean = false;
        getName(): string {
            throw new Error("Method not implemented.");
        }
        getLabel(): string {
            throw new Error("Method not implemented.");
        }

        getValue() {
            throw new Error("Method not implemented.");
        }
        setValue(value: any, options?: SetValueOptions | undefined): void {
            throw new Error("Method not implemented.");
        }
        setValueToUndefined(options?: SetValueOptions | undefined): void {
            throw new Error("Method not implemented.");
        }
        getDataType(): string | null {
            throw new Error("Method not implemented.");
        }
        getDataTypeLabel(): string {
            throw new Error("Method not implemented.");
        }
        getPropertyName(): string {
            return this.getName();
        }        

        isChanged: boolean = false;
        saveIntoInstanceState(key: string, value: ValidTypesForInstanceStateStorage | undefined): void {
            throw new Error("Method not implemented.");
        }
        getFromInstanceState(key: string): ValidTypesForInstanceStateStorage | undefined {
            throw new Error("Method not implemented.");
        }
        getValidator(errorCode: string): IValidator | null {
            throw new Error("Method not implemented.");
        }
        isEnabled(): boolean {
            throw new Error("Method not implemented.");
        }
        setEnabled(enabled: boolean): void {
            throw new Error("Method not implemented.");
        }
    }
    test('Passing object with interface match returns same object.', () => {
        let testItem = new TestIFieldValueHostImplementation();

        expect(toIFieldValueHost(testItem)).toBe(testItem);
    });
  
    test('StaticValueHost return null.', () => {
        let vhm = new MockValueHostsManager(new MockJivsServices(false, false));
        let testItem = new StaticValueHost(vhm, {
                name: 'Field1',
                label: 'Label1'
            },
            {
                name: 'Field1',
                value: undefined
            });
        expect(toIFieldValueHost(testItem)).toBeNull();
    });            
    test('CalcValueHost return null.', () => {
        let vhm = new MockValueHostsManager(new MockJivsServices(false, false));
        let testItem = new CalcValueHost(vhm, {
                name: 'Field1',
                label: 'Label1',
                calcFn: (host, manager)=> 0
            },
            {
                name: 'Field1',
                value: undefined
            });
        expect(toIFieldValueHost(testItem)).toBeNull();
    });            
    test('Non-matching interface returns null.', () => {
        let testItem = {};
        expect(toIFieldValueHost(testItem)).toBeNull();
    });
    test('null returns null.', () => {
        expect(toIFieldValueHost(null)).toBeNull();
    });
    test('Non-object returns null.', () => {
        expect(toIFieldValueHost(100)).toBeNull();
    });
});

describe('toIFieldValueHostCallbacks function', () => {
    test('Passing actual FieldValueHost matches interface returns same object.', () => {
        let testItem = new MockValueHostsManager(new MockJivsServices(false, false));

        expect(toIFieldValueHostCallbacks(testItem)).toBe(testItem);
    });
    class TestIFieldValueHostCallbacksImplementation implements IFieldValueHostCallbacks {
        onValueChanged(vh: IValueHost, old: any) { }
        onValueHostInstanceStateChanged(vh: IValueHost, state: ValueHostInstanceState) { }
        onTextValueChanged(vh: IValidatableValueHostBase, old: any) { }
        onValueHostValidationStateChanged(vh: IValidatableValueHostBase, validationState: ValueHostValidationState) { }
    }
    test('Passing object with interface match returns same object.', () => {
        let testItem = new TestIFieldValueHostCallbacksImplementation();

        expect(toIFieldValueHostCallbacks(testItem)).toBe(testItem);
    });
    test('Non-matching interface returns null.', () => {
        let testItem = {};
        expect(toIFieldValueHostCallbacks(testItem)).toBeNull();
    });
    test('null returns null.', () => {
        expect(toIFieldValueHostCallbacks(null)).toBeNull();
    });
    test('Non-object returns null.', () => {
        expect(toIFieldValueHostCallbacks(100)).toBeNull();
    });
});

describe('No mocks!', () => {
    function createServices(logLevel: LoggingLevel = LoggingLevel.Debug): IJivsServices {
        let services = createJivsServicesForTesting();
        services.loggerService.minLevel = logLevel;
        return services;
    }

    test('setValue with validate=true, onValueHostValidationStateChanged called', () => {
        let onValidateResult: ValueHostValidationState | null = null;
        let services = createServices(LoggingLevel.Error);
        let logger = services.loggerService as ConsoleLoggerService;
        logger.overrideMinLevelWhen({
            feature: 'ValueHost',
            identity: 'Field1'
        });
        logger.overrideMinLevelWhen({
            category: LoggingCategory.Result,
        });
        let vmConfig = <ValueHostsManagerConfig>{
            services: services,
            valueHostConfigs: [],
            onValueHostValidationStateChanged: (vh, vr) => {
                onValidateResult = vr;
            }
        };
        vmConfig.valueHostConfigs.push(<FieldValueHostConfig>{
            valueHostType: ValueHostType.Field,
            name: 'Field1',
            lookupKey: LookupKey.String,
            validatorConfigs: [{
                errorMessage: 'error',
                conditionConfig: {
                    conditionType: ConditionType.RequireText
                }
            }]
        });

        // let builder = createBuilder({
        //     onValueHostValidationStateChanged: (vh, vr) => {
        //         onValidateResult = vr;
        //     },
        // }, services);
        // builder.field('Field1').requireText('error');
        let vhm = new ValueHostsManager(vmConfig);
        let vh = vhm.vh.field('Field1');
        vh.setValues('', '', { validate: true });   // empty is invalid

        expect(onValidateResult).toEqual(<ValueHostValidationState>{
            isValid: false,
            issuesFound: [{
                errorCode: ConditionType.RequireText,
                valueHostName: 'Field1',
                severity: ValidationSeverity.Severe,
                errorMessage: 'error',
                summaryMessage: 'error',
                doNotSave: true
            } ],
            doNotSave: true,
            asyncProcessing: false,
            status: ValidationStatus.Invalid,
            corrected: false
        });
    });        
});