on: push
name: 🚀 Deploy docs to jivs.peterblum.com
description: FTPs files from /docs to jivs.peterblum.com/typedoc, replacing existing
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: sec720.servdns.com
        username: PeterBlum
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./docs/
        server-dir: TypeDoc/
        dry-run: true